### PR TITLE
Add resourceVersion to CronJob metrics

### LINKED ISSUE #1433: Adding resourceVersion to CronJob metrics?
**What would you like to be added**:

For deployments we already have a generation metric, which helps to see whether a deployment changed. We do not have such a metric for CronJobs -- they don't have such metadata at all. We could export the resourceVersion metadata as label though, similar to what ConfigMaps, Secrets and Ingress resources have.

**Why is this needed**:

#500 was closed due to being inactive, but is still an issue. We have an alert that notifies us whenever the calculated CronJob start date passed. Something like `and changes(kube_cronjob_metadata_resource_version[24h])` would help to mitigate the issue.

**Describe the solution you'd like**

Mostly copy-paste the solution from configmaps.

**Additional context**

I'm fine with providing the code, if we have agreement on this being a good thing to have.

<sup>Jens Erat <jens.erat@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

### PR DESCRIPTION
**Pull request by pkbhowmick**
Signed-off-by: Pulak Kanti Bhowmick <pkbhowmick007@gmail.com>

**What this PR does / why we need it**:
This PR adds resourceVersion metrics for CronJob resource.

**Which issue(s) this PR fixes**:
Fixes #1433

### CODE REVIEW

**Comment by tariq1890** [comment]
I think this is okay to add since it's useful to track changes in the `CronJob` manifest.

cc @lilic @brancz @mrueg waiting on a second approval in case one of you needed a chance to look at this

/approve
/hold

**Comment by pkbhowmick** [comment]
waiting for the second approval @brancz @lilic @mrueg. Can anyone please look into this? I am so excited to contribute into this project. :smile:

**Review by lilic — APPROVED** [review]
/lgtm 

Thank you!
/hold cancel

**Pull request merged**
