### PR TITLE
revert: Revert sync-based commits

### PR DESCRIPTION
**Pull request by rexagod**
This reverts commit 98ade63, reversing changes made to d68bad2.

***

`main` was merged into `release-2.10` to make the whole "merge back to `main`" process predictable, so there's no conflicts, while creating a `v2.10.1` release from the `HEAD~2` commit (the last commit before the merge `main` into `release-2.10` happened). But none of that applies anymore since we will be letting release branches diverge going forward, allowing for easier patch releases, be it CVEs, critical fixes, etc. without the need to merge back into main. Whether we'll do the same for minor version releases as well, is up for discussion at this moment.

Also note that the last commit regarding lint fixes was done owing to the `markdownlint` check that got in during the merge, which is also reverted in this PR.

cc @dgrisonnet

### CODE REVIEW

**Comment by dgrisonnet** [comment]
Wait why do we have are we building with go 1.21 (https://github.com/kubernetes/kube-state-metrics/blob/release-2.10/Dockerfile) on release-2.10, but the go version is marked to be 1.20.8 (https://github.com/kubernetes/kube-state-metrics/blob/release-2.10/Makefile#L19)?

**Comment by dgrisonnet** [comment]
An additional reason for not merging back

**Comment by dgrisonnet** [comment]
@rexagod should we perhaps revert everything since the v2.10.0 cut and then I cherry-pick https://github.com/kubernetes/kube-state-metrics/pull/2190 properly and you do https://github.com/kubernetes/kube-state-metrics/pull/2192 again?

**Comment by rexagod** [comment]
Seems like https://github.com/kubernetes/kube-state-metrics/pull/2213#issuecomment-1748866190 came in from 435aa5a0. Closing this in favor of https://github.com/kubernetes/kube-state-metrics/pull/2213#issuecomment-1748890182.

**Pull request closed without merging**
