### PR TITLE
*: Cut v1.6.0-rc.2

### PR DESCRIPTION
**Pull request by mxinden**

### CODE REVIEW

**Comment by andyxning** [comment]
@brancz Can you please tag `v1.6.0-rc.1` and `v1.6.0-rc.2` and push it to the github. :)

**Comment by andyxning** [comment]
Seems i have no authorization.

**Comment by mxinden** [comment]
@andyxning I tagged both releases and pushed quay.io/coreos/kube-state-metrics:v1.6.0-rc.2 .

**Pull request merged**
