### PR TITLE
prefer protobuf instead of just json format

### PR DESCRIPTION
**Pull request by andyxning**
**What this PR does / why we need it**:
This PR will prefer protobuf format when communicating with apiserver instead of just json.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #264

### CODE REVIEW

**Comment by brancz** [comment]
Have you tried this against a couple of clusters? I recall that in an earlier attempt of this, there were some issues left when changing the accept header to proto.

**Comment by brancz** [comment]
I tried running this against a cluster and quickly got this kind of output for all list-watches:

```
E0611 10:16:39.155112   17021 streamwatcher.go:109] Unable to decode an event from the watch stream: invalid character '\x00' looking for beginning of value
W0611 10:16:39.155334   17021 reflector.go:341] k8s.io/kube-state-metrics/pkg/collectors/collectors.go:91: watch of *v1.ConfigMap ended with: very short watch: k8s.io/kube-state-metrics/pkg/collectors/collectors.go:91: Unexpected watch close - watch lasted less than a second and no items received
E0611 10:16:39.633030   17021 streamwatcher.go:109] Unable to decode an event from the watch stream: invalid character '\x00' looking for beginning of value
W0611 10:16:39.633185   17021 reflector.go:341] k8s.io/kube-state-metrics/pkg/collectors/collectors.go:91: watch of *v1.Node ended with: very short watch: k8s.io/kube-state-metrics/pkg/collectors/collectors.go:91: Unexpected watch close - watch lasted less than a second and no items received
E0611 10:16:39.633250   17021 streamwatcher.go:109] Unable to decode an event from the watch stream: invalid character '\x00' looking for beginning of value
W0611 10:16:39.633297   17021 reflector.go:341] k8s.io/kube-state-metrics/pkg/collectors/collectors.go:91: watch of *v1.Endpoints ended with: very short watch: k8s.io/kube-state-metrics/pkg/collectors/collectors.go:91: Unexpected watch close - watch lasted less than a second and no items received
E0611 10:16:41.227737   17021 streamwatcher.go:109] Unable to decode an event from the watch stream: invalid character '\x00' looking for beginning of value
W0611 10:16:41.227969   17021 reflector.go:341] k8s.io/kube-state-metrics/pkg/collectors/collectors.go:91: watch of *v1.Node ended with: very short watch: k8s.io/kube-state-metrics/pkg/collectors/collectors.go:91: Unexpected watch close - watch lasted less than a second and no items received
E0611 10:16:41.600676   17021 streamwatcher.go:109] Unable to decode an event from the watch stream: invalid character '\x00' looking for beginning of value
W0611 10:16:41.600788   17021 reflector.go:341] k8s.io/kube-state-metrics/pkg/collectors/collectors.go:91: watch of *v1.Endpoints ended with: very short watch: k8s.io/kube-state-metrics/pkg/collectors/collectors.go:91: Unexpected watch close - watch lasted less than a second and no items received
```

**Comment by andyxning** [comment]
> Have you tried this against a couple of clusters? 

Actually no. I have just test that the `Accept: application/vnd.kubernetes.protobuf,application/json` can fetch response in protobuf format in my postman.

**Comment by caesarxuchao** [comment]
This should work, does the watch still fail? Please ping me on slack if this still has problems.

**Comment by andyxning** [comment]
@caesarxuchao Yes, it works. We have test it locally. Maybe what i want to know is that what is the requirement for enable protobuf support in client-go since there is no wiki nor examples about this.

@brancz it should be ok to merge this for now, i think. ~

**Pull request merged**
