### PR TITLE
Merge performance optimizations into master

### PR DESCRIPTION
**Pull request by mxinden**
**What this PR does / why we need it**:

Given that all collectors are now updated to the new performance optimized architecture, we can go ahead and merge the optimizations into master. What do you all think?

### CODE REVIEW

**Comment by mxinden** [comment]
Mhh, did the @k8s-ci-robot not sign the contributor license agreement?

**Comment by brancz** [comment]
This has been a pretty huge effort, thanks for all your involvement and hard work @mxinden! Nice work! :tada:

**Comment by mxinden** [comment]
Thanks. :)

How do you want to proceed with this patch? I can rebase it on top of master without  the merge commits which would then pass the CLA check.

**Comment by brancz** [comment]
@mxinden let's do that.

**Comment by mxinden** [comment]
Closing here in favour of https://github.com/kubernetes/kube-state-metrics/pull/601 as I can't change the origin of a PR.

**Pull request closed without merging**
