### PR TITLE
Enable unconvert linter

### PR DESCRIPTION
**Pull request by bvwells**
**What this PR does / why we need it**:
This PR enables the unconvert linter and fixes various issues across the code base where type conversion is unnecessary. The PR aims to improve code readability.

Hope this is useful!

### CODE REVIEW

**Comment by tariq1890** [comment]
Thanks for this PR @bvwells . This LGTM. I was wondering why `unconvert` doesn't catch some of the redundant type conversions in [metrics_handler.go](https://github.com/kubernetes/kube-state-metrics/blob/f3d41de450a1f72397ae935af3c2a58d7bb8afa4/pkg/metricshandler/metrics_handler.go#L111), [metric_test.go](https://github.com/kubernetes/kube-state-metrics/blob/bbb1dca85dc3f59132dcbcc18be3da8514fcc109/pkg/metric/metric_test.go#L64), and [listwatch.go](https://github.com/kubernetes/kube-state-metrics/blob/84d61f9a93a2705cee7ac2a578e5eed04ede73b7/pkg/sharding/listwatch.go#L76).

**Comment by bvwells** [comment]
Thanks for the review @tariq1890. Some comments on the code you identified.

- metric_test.go - looks like it is due to this: https://github.com/mdempsky/unconvert/blob/3ecd357795aff6024d9b038acc536bb7090c4e2f/unconvert.go#L419
-  metrics_handler.go, listwatch.go - I suspect that unconvert does not handle situations where the type definition uses the same underlying type. I'll have a little dig to check that this is the case.

**Comment by tariq1890** [comment]
Not a problem. Feel free to remove the rest in another PR. Will approve this.

Thanks @bvwells!

**Pull request merged**
