### PR TITLE
Add PodDisruptionBudget metrics

### LINKED ISSUE #546: Add metrics for PodDisruptionBudget objects
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

**What you expected to happen**:
It would be cool to have metrics for PDB objects for visibility into availability and possible disruptions. I can start working on this if it sounds like a reasonable proposal.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kube-state-metrics image version

### PR DESCRIPTION
**Pull request by gregory-lyons**
**What this PR does / why we need it**:
Adds metrics for PodDisruptionBudget

**Which issue(s) this PR fixes** :
Fixes #546

### CODE REVIEW

**Comment by gregory-lyons** [comment]
anyone get a chance to look at this?

**Comment by brancz** [comment]
Did you have a chat with @mxinden about rebasing this on top of his in-progress architecture changes?

**Comment by gregory-lyons** [comment]
I mentioned it here: https://github.com/kubernetes/kube-state-metrics/issues/546#issuecomment-426151622

If the architecture changes are close to merge, I can rebase. @mxinden what's the current status?

**Comment by mxinden** [comment]
@gregory-lyons https://github.com/kubernetes/kube-state-metrics/pull/534 merged today. Let me know if I can help you adapting to the changes. I a sorry for the inconvenience.

**Comment by gregory-lyons** [comment]
@mxinden @brancz I've now rebased on top of #534

**Comment by gregory-lyons** [comment]
@brancz anything else I need to do on my end to get this merged? Thanks for review

**Comment by brancz** [comment]
Actually not sure why it didn’t merge it.

/approve
/lgtm

**Pull request merged**
