### PR TITLE
Clean up `select {}`

### PR DESCRIPTION
**Pull request by CatherineF-dev**
**What this PR does / why we need it**:

**How does this change affect the cardinality of KSM**: *(increases, decreases or does not change cardinality)* N/A

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by CatherineF-dev** [comment]
cc @mrueg to review.

Does this `select {}` have some special purposes?

**Comment by mrueg** [comment]
AFAIK the select here is used to block similar to an infinite for loop.

**Comment by rexagod** [comment]
Yep, closing.

**Pull request closed without merging**
