### PR TITLE
Address gocyclo complexity warnings

### LINKED ISSUE #1887: Address lint reports
According to [this](https://goreportcard.com/report/github.com/kubernetes/kube-state-metrics) (which we have a pointer to at the top of the README), `gocyclo` is the only linter not happy with the codebase in it's current state.

Please address these warnings, or add comments explaining why we need to [ignore them](https://github.com/fzipp/gocyclo#ignoring-individual-functions) in the codebase, so they aren't reported again.

### PR DESCRIPTION
**Pull request by venkatbvc**
**What this PR does / why we need it**: Fixed the lint issues highlighted in [this](https://goreportcard.com/report/github.com/kubernetes/kube-state-metrics) report.

**How does this change affect the cardinality of KSM**: No change.

**Which issue(s) this PR fixes**: Fixes #1887.

### CODE REVIEW

**Comment by rexagod** [comment]
I can still see `gocyclo` warnings for complexity measures of more than 15, (same as what the aforementioned website uses](https://goreportcard.com/report/github.com/kubernetes/kube-state-metrics#gocyclo) to run the linter on this repository.

```
docker run -v "/home/rexagod/repositories/work/kube-state-metrics:/mnt" koalaman/shellcheck:stable ./scripts/generate-help-text.sh ./tests/compare-sharding.sh ./tests/compare_benchmarks.sh ./tests/e2e.sh
>> checking license header
golangci-lint run
pkg/options/types.go:242:1: cyclomatic complexity 16 of func `(*LabelsAllowList).Set` is high (> 15) (gocyclo)
func (l *LabelsAllowList) Set(value string) error {
^
internal/store/persistentvolume.go:214:1: cyclomatic complexity 18 of func `createPVInfoFamilyGenerator` is high (> 15) (gocyclo)
func createPVInfoFamilyGenerator() generator.FamilyGenerator {
^
pkg/app/server_test.go:140:1: cyclomatic complexity 17 of func `TestFullScrapeCycle` is high (> 15) (gocyclo)
func TestFullScrapeCycle(t *testing.T) {
^
pkg/app/server.go:130:1: cyclomatic complexity 16 of func `RunKubeStateMetrics` is high (> 15) (gocyclo)
func RunKubeStateMetrics(ctx context.Context, opts *options.Options) error {
^
make: *** [Makefile:45: lint] Error 1
```

**Comment by venkatbvc** [comment]
@rexagod  I will check and push the changes. 
can i run the below command locally? I will change paths 
docker run -v "/home/rexagod/repositories/work/kube-state-metrics:/mnt" koalaman/shellcheck:stable ./scripts/generate-help-text.sh ./tests/compare-sharding.sh ./tests/compare_benchmarks.sh ./tests/e2e.sh

**Comment by rexagod** [comment]
My bad, I should've mentioned the steps. You'll need to:

- 	Add the following to the `linter-settings` in `.golangci.yml`.
	```yaml
	gocyclo: 
		min-complexity: 15
	```
- Run `make lint`.

**Comment by venkatbvc** [comment]
@rexagod  I have pushed the changes. and fixed. lint has lot of unused variable errors. Do you want me push changes for them also?

**Comment by venkatbvc** [comment]
@rexagod Can you please check the changes, one Unit test was failing. It failed in the main branch also. So i did not fix. Lint errors related to unused variables are there. Let me know if you want me to fix them

**Comment by rexagod** [comment]
There seems to be +- ~4500 changes in this PR. I would suggest breaking this up into logical bits (some sort of grouping) so that it's easier to review, and no bugs creep in on the account of being missed out by the reviewers due to the sheer size of the PR.

**Comment by venkatbvc** [comment]
@rexagod  Sure. I will make changes for cyclomatic complexity per resource and push. Let me if the approach is fine.  i will do it in a new pull request.

**Pull request closed without merging**
