### PR TITLE
fix API Endpoint for CronJobs

### PR DESCRIPTION
**Pull request by cpointner**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kube-state-metrics/311)

### CODE REVIEW

**Comment by zouyee** [comment]
At first, please sign cla, thanks you!

**Comment by brancz** [comment]
@zouyee he mentioned on the other PR that the CLA is in the works :slightly_smiling_face: (RE: https://github.com/kubernetes/kube-state-metrics/pull/291#discussion_r155263751)

**Comment by cpointner** [comment]
@brancz, @zouyee: CLA is now signed

**Comment by brancz** [comment]
Thanks! And congrats on your first contribution to the Kubernetes org! :slightly_smiling_face:

**Comment by cpointner** [comment]
@brancz Thanks for the warm welcome! :smile:

**Pull request merged**
