### PR TITLE
compile kube-state-metrics with go1.13

### PR DESCRIPTION
**Pull request by tariq1890**

### CODE REVIEW

**Comment by tariq1890** [comment]
/hold

Unhold when #882 is merged.

**Comment by LiliC** [comment]
@tariq the other PR is merged, we need to rebase and retest now.

**Comment by tariq1890** [comment]
@LiliC Looks like #882 needs to be backported to the `release-1.8` branch to work :(.

Given that #882 is a harmless change and necessary, I'd vote for the backport. That way, we can unblock this PR.

**Comment by LiliC** [comment]
@tariq1890 what’s the reason it needs to be backported? Not objecting at all, just curious.

**Comment by tariq1890** [comment]
So the benchmark tests are failing because of an unsuccessful branch switch. This is happening because the `go 1.13` runtime auto-adds the go version to the `go.mod` manifest file if not present. The only way to get around this inconvenience is to add the `go version` pin to the `release-1.8` branch which does not have it yet. This way `go 1.13` won't introduce the unexpected change and cause the branch checkout to fail while the benchmark tests are running.

**Comment by LiliC** [comment]
@tariq1890  Makes sense, (what go is doing doesn't :D) but makes sense to backport. Go ahead!

**Comment by tariq1890** [comment]
@LiliC Ready for review :)

**Pull request merged**
