### PR TITLE
Remove namespace from PersistentVolume metrics

### PR DESCRIPTION
**Pull request by tcolgate**
Remove namespace from PersistentVolume metrics as PersistentVolume is not namespace scoped.

### CODE REVIEW

**Comment by andyxning** [comment]
The failure is unexpected. Will take a look at it.

**Comment by tcolgate** [comment]
@andyxning 
My bad, I checked in a change I need locally to stop the cronjob tests complaining. Fixed

**Comment by tcolgate** [comment]
@andyxning 
Rebase also brought some references to the namespace label back.
All fixed now.

**Pull request merged**
