### PR TITLE
[PDNM] chore: comment bench results on PR

### PR DESCRIPTION
**Pull request by rexagod**
**What this PR does / why we need it**: Comment benchmark outputs on the PR, for better visibility, and to make sure we don't miss out on catching potential bottlenecks.

**How does this change affect the cardinality of KSM**: None.

### CODE REVIEW

**Comment by mrueg** [comment]
Hah you read my mind. I think commenting will be a bit too noisy. We can provide a nicer table output in the github actions check format though

**Comment by rexagod** [comment]
Do you think it'd be fine to keep the bench results implicit? I thought we may want to post them on the PR (and remove older ones when a new one is posted), to make the benchmarks more apparent in a manner that they are never missed.

For the noisy part, I was wondering we could do something like (the click-to-expand element),

### KSM Benchmark Output

<details>
<summary>Details</summary>

```
foo
```

</details>

I'm neutral on this. LMK if you think we'd be better off without this, and I'll create a PR for improving the format in the CI logs themselves.

**Comment by mrueg** [comment]
I'm afraid of too much noise if someone force pushes several times. 
Do you think it would be possible to only comment if benchmarks change let's say more than 5% to the baseline?

**Pull request closed without merging**
