### PR TITLE
use latest version of k8s.io/klog

### PR DESCRIPTION
**Pull request by tariq1890**
updating to `v0.3.0`

### CODE REVIEW

**Comment by andyxning** [comment]
Thanks for taking care of this! @tariq1890 

/lgtm
/approve

**Comment by andyxning** [comment]
@tariq1890 Seems that `vendor/modules.txt` is maintained manually not by the golang module system. Could we remove it?

**Comment by tariq1890** [comment]
I am note sure about that. I believe it's auto-generated by go mod.

**Comment by andyxning** [comment]
@tariq1890 Yes, you're right. `go mod vendor` will generate it.

**Pull request merged**
