### PR TITLE
*: Cut v1.7.0 release

### PR DESCRIPTION
**Pull request by LiliC**
**What this PR does / why we need it**:
Cutting v1.7.0 release because, after a testing period of 7 days, there were no additional bugs found or features introduced.

As agreed in https://github.com/kubernetes/kube-state-metrics/pull/816#issuecomment-512158611

cc @tariq1890 @brancz

### CODE REVIEW

**Comment by LiliC** [comment]
cc @loburm @piosz could you take care of publish the image to gcr.io when this is approved, thanks!

**Comment by tariq1890** [comment]
Let's update the version support matrix as well.

**Comment by LiliC** [comment]
@tariq1890 done, thanks!

**Comment by tariq1890** [comment]
Thanks @LiliC. I missed to point out one more place. Let's update here as well https://github.com/kubernetes/kube-state-metrics/blob/master/README.md#container-image

**Comment by LiliC** [comment]
@tariq1890 already did that :)

**Comment by brancz** [comment]
Thanks a lot for kicking this off!

/hold cancel
/lgtm

**Comment by tariq1890** [comment]
Awesome! Once published, we should merge the release branch into master.

**Comment by brancz** [comment]
Container image published at `quay.io/coreos/kube-state-metrics:v1.7.0` and also now the `latest` image.

**Comment by loburm** [comment]
I have pushed all images to k8s.gcr.io.

**Pull request merged**
