### PR TITLE
[release-2.1] Backport #1610

### PR DESCRIPTION
**Pull request by ahmed-mez**
**What this PR does / why we need it**:

Backport https://github.com/kubernetes/kube-state-metrics/pull/1610

@mrueg @dgrisonnet @fpetkovski

### CODE REVIEW

**Comment by mrueg** [comment]
We don't have a regular releases planned for v2.1 and would only do it upon request. General we encourage users to run the latest version of kube-state-metrics.

**Comment by dgrisonnet** [comment]
@mrueg since this PR has your approval and the other maintainers aren't replying to apply the label, I think we should merge this PR manually.

**Comment by mrueg** [comment]
@dgrisonnet agreed, merged it manually.

**Pull request merged**
