### PR TITLE
Fix gzip writer

### LINKED ISSUE #1371: Metric encoding is broken when using --enable-gzip-encoding flag.
**What happened**: Ive enabled gzip compression for kube-state-metrics using extraArgs param in helm chatr  (--enable-gzip-encoding)

**What you expected to happen**: i expect metrics to be compressed but accessible

**How to reproduce it (as minimally and precisely as possible)**: Deploy latest kube-state-metrics chart 2.11.0 with extraAgrs that contains --enable-gzip-encoding param. Wait till kube-state-metrics pod starts. Try to access metrics using any browser. It will fail with "Failed to load resource: net::ERR_CONTENT_DECODING_FAILED" message in console.

**Anything else we need to know?**:

**Environment**: 
- kube-state-metrics version: v1.9.7
- Kubernetes version (use `kubectl version`): v1.17.13
- Cloud provider or hardware configuration: AWS
- Other info:

### PR DESCRIPTION
**Pull request by lou-lan**
**What this PR does / why we need it**:
Fix gzip writer.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1371

### CODE REVIEW

**Comment by tariq1890** [comment]
Thanks for the PR @lou-lan ! Can you retarget this PR to the `release-1.9` branch?

**Comment by lou-lan** [comment]
@tariq1890 I've resubmitted.

**Comment by brancz** [comment]
My apologies @lou-lan, I'm not sure why Tariq is not replying. I'd be happy to merge this into the `release-2.0` branch and then merge that branch back into master. If Tariq insists he can backport it to 1.9 and do a 1.9 release, but the majority of our efforts are towards 2.0 now.

**Comment by lou-lan** [comment]
@brancz I have changed the target branch, please review it.

**Comment by brancz** [comment]
Fantastic, thank you!

/lgtm
/approve

**Pull request merged**
