### PR TITLE
bump deployment kube-state-metrics version to v0.4.1

### PR DESCRIPTION
**Pull request by andyxning**
Bump deployment.yml kube-state-metrics version to v0.4.1.

/cc @brancz @fabxc

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kube-state-metrics/88)

### CODE REVIEW

**Comment by shamil** [comment]
I think the image wasn't pushed to the registry yet

**Comment by andyxning** [comment]
@shamil Yes, you're right. v0.4.1 has not been pushed to the registry. I have test this with `docker pull gcr.io/google_containers/kube-state-metrics:v0.4.1`.

```
Pulling repository gcr.io/google_containers/kube-state-metrics
Tag v0.4.1 not found in repository gcr.io/google_containers/kube-state-metrics
``` 

/ping @piosz @bgrant0607

**Comment by piosz** [comment]
I've pushed:
```
gcr.io/google_containers/kube-state-metrics:v0.4.0
gcr.io/google_containers/kube-state-metrics:v0.4.1
```
Please check whether it works.

**Comment by andrewhowdencom** [comment]
Pulling works OK. 
```
$ docker pull gcr.io/google_containers/kube-state-metrics:v0.4.1
v0.4.1: Pulling from google_containers/kube-state-metrics
f791b6b985ee: Pull complete 
Digest: sha256:f10a63848dbb9823ab2b870e5d656107bf5c4905d33ba7ecb4e4165c228787d2
Status: Downloaded newer image for gcr.io/google_containers/kube-state-metrics:v0.4.1
```

**Comment by andyxning** [comment]
@piosz 👍 

v0.4.0 works well, too. 😄 
```
$ docker pull gcr.io/google_containers/kube-state-metrics:v0.4.0
v0.4.0: Pulling from google_containers/kube-state-metrics
Digest: sha256:249d036d5cebecf86d0f7dc3894aec249a1ac0107cd72678f7beea80df03dc50
Status: Image is up to date for gcr.io/google_containers/kube-state-metrics:v0.4.0
```

Friendly ping @brancz @fabxc

**Pull request merged**
