### PR TITLE
fix a broken link to './kubernetes/autosharding'

### PR DESCRIPTION
**Pull request by jiyeonseo**
**What this PR does / why we need it**:
fixed a broken link to autosharding path

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by brancz** [comment]
Thanks! Could you sign the CLA? Then this is good to go.

/lgtm

**Comment by jiyeonseo** [comment]
I signed it

**Comment by brancz** [comment]
Looks like there is a conflict now.

**Pull request merged**
