### PR TITLE
allow metric labels by default

### LINKED ISSUE #1270: Label information is not exported to kube_node_labels metrics
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
The [Node Metrics documentation](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/node-metrics.md#node-metrics) has a description of `kube_node_labels`, but `kube_node_labels` is not export labels when using `v2.0.0-alpha.1`.

- `kube-state-metrics:v2.0.0-alpha.1`

    Labels information is not export
    ```diff
    # HELP kube_node_labels Kubernetes labels converted to Prometheus labels.
    # TYPE kube_node_labels gauge
    - kube_node_labels 1
    - kube_node_labels 1
    - kube_node_labels 1
    - kube_node_labels 1
    # HELP kube_node_role The role of a cluster node.
    ```
    

- `kube-state-metrics:v1.9.7`
Using `v1.9.7` in same environment exports Labels.

    ```diff
    # HELP kube_node_labels Kubernetes labels converted to Prometheus labels.
    # TYPE kube_node_labels gauge
    + kube_node_labels{node="kind-worker",label_beta_kubernetes_io_arch="amd64",label_beta_kubernetes_io_os="linux",label_kubernetes_io_arch="amd64",label_kubernetes_io_hostname="kind-worker",label_kubernetes_io_os="linux"} 1
    + kube_node_labels{node="kind-control-plane",label_beta_kubernetes_io_arch="amd64",label_beta_kubernetes_io_os="linux",label_ingress_ready="true",label_kubernetes_io_arch="amd64",label_kubernetes_io_hostname="kind-control-plane",label_kubernetes_io_os="linux",label_node_role_kubernetes_io_master=""} 1
    + kube_node_labels{node="kind-worker3",label_beta_kubernetes_io_arch="amd64",label_beta_kubernetes_io_os="linux",label_kubernetes_io_arch="amd64",label_kubernetes_io_hostname="kind-worker3",label_kubernetes_io_os="linux"} 1
    + kube_node_labels{node="kind-worker2",label_beta_kubernetes_io_arch="amd64",label_beta_kubernetes_io_os="linux",label_kubernetes_io_arch="amd64",label_kubernetes_io_hostname="kind-worker2",label_kubernetes_io_os="linux"} 1
    # HELP kube_node_role The role of a cluster node.
    ```

**What you expected to happen**:
`kube_node_labels` is exported Labels when using `v2.0.0-alpha.1`.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a cluster using kind.

    ```yaml
    kind: Cluster
    apiVersion: kind.x-k8s.io/v1alpha4
    nodes:
    - role: control-plane
      image: kindest/node:v1.19.1
    - role: worker
      image: kindest/node:v1.19.1
    - role: worker
      image: kindest/node:v1.19.1
    - role: worker
      image: kindest/node:v1.19.1
    ```

2. install kube-state-metrics from https://github.com/kubernetes/kube-state-metrics/tree/master/examples/standard. 

**Anything else we need to know?**:
The other "kube_XXXX_labels" metrics are in the same state. I have confirmed that the following metrics are the same in my environment.

```
# TYPE kube_daemonset_labels gauge
kube_daemonset_labels 1

# TYPE kube_deployment_labels gauge
kube_deployment_labels 1

# TYPE kube_endpoint_labels gauge
kube_endpoint_labels 1

# TYPE kube_ingress_labels gauge
kube_ingress_labels 1

# TYPE kube_job_labels gauge
kube_job_labels 1

# TYPE kube_namespace_labels gauge
kube_namespace_labels 1

# TYPE kube_node_labels gauge
kube_node_labels 1

# TYPE kube_pod_labels gauge
kube_pod_labels 1

# TYPE kube_replicaset_labels gauge
kube_replicaset_labels 1

# TYPE kube_secret_labels gauge
kube_secret_labels 1

# TYPE kube_service_labels gauge
kube_service_labels 1

# TYPE kube_statefulset_labels gauge
kube_statefulset_labels 1
```

**Environment**:
- Kubernetes version (use `kubectl version`): `v1.19.3`
- Kube-state-metrics image version: `v2.0.0-alpha.1`

### PR DESCRIPTION
**Pull request by jw-s**
Signed-off-by: Joel Whittaker-Smith <jdws.dev@gmail.com>

**What this PR does / why we need it**:
It adds each metric's default labels to be allowed for label/annotation related metrics
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1270

### CODE REVIEW

**Comment by jw-s** [comment]
@lilic Here's the bugfix

**Comment by dgrisonnet** [comment]
Thank you for looking into this @jw-s!

I just have a small comment regarding your PR. Since we know that all the k8s labels/annotations are prepended by a fixed prefix when converted to prom labels, wouldn't it be easier to wait for #1247 and allow by default all the labels that don't have this prefix? For example with the following regex for labels: `^(?!label_).*`.

**Comment by lilic** [comment]
> I just have a small comment regarding your PR. Since we know that all the k8s labels/annotations are prepended by a fixed prefix when converted to prom labels, wouldn't it be easier to wait for #1247 and allow by default all the labels that don't have this prefix? For example with the following regex for labels: ^(?!label_).*.


@dgrisonnet I would prefer to specify the allowed ones in a list rather than wildcard as that can miss things, so I like this approach more. #1247 will not land in release-2.0 and this would as its fixing a bug.

**Comment by jw-s** [comment]
@lilic I'm sorry I don't get you, do I need to do anything?

**Comment by lilic** [comment]
@jw-s current approach is not exactly the right direction we want to go with, so I will give it a shot and ping you for your review when I open a PR, hope that sounds good to you? Thanks!!

**Comment by jimmyseto** [comment]
> @jw-s current approach is not exactly the right direction we want to go with, so I will give it a shot and ping you for your review when I open a PR, hope that sounds good to you? Thanks!!

@lilic @jw-s - i know v2.0.0 isn't completely out the door yet, but where do we currently stand with improving label support (i.e. enabling users to easily allow metric labels)?  i think the following issues essentially boil down to the same ask:

https://github.com/kubernetes/kube-state-metrics/issues/1309
https://github.com/kubernetes/kube-state-metrics/issues/1246

thanks in advance!

**Pull request closed without merging**
