### PR TITLE
feat: Add new metric kube_job_status_suspended

### PR DESCRIPTION
**Pull request by Indresh2410**
**What this PR does / why we need it**:
Kubernetes has released a new feature which can suspend a job
https://kubernetes.io/docs/concepts/workloads/controllers/job/#suspending-a-job

Emit metrics if the job is suspended

**How does this change affect the cardinality of KSM**: *(increases, decreases or does not change cardinality)*
Increases

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*
Fixes # https://github.com/kubernetes/kube-state-metrics/issues/2511

### CODE REVIEW

**Comment by CatherineF-dev** [comment]
We can follow other metrics to have only 2 labels: job_name and namespace name.
https://github.com/kubernetes/kube-state-metrics/blob/a6cb8ded1e9c3688e475f94e0dabbff35a5d2396/docs/metrics/workload/job-metrics.md

**Comment by Indresh2410** [comment]
Thanks @CatherineF-dev . Have addressed them. Can you please check once?

**Comment by Indresh2410** [comment]
@CatherineF-dev have updated doc. Because of which label got removed. Can you please check once again. SFIC

**Comment by mrueg** [comment]
Can you rebase this on latest main branch? Thanks!

**Comment by mrueg** [comment]
@Indresh2410 it looks like the newline is missing in the doc. Could you add it?

**Comment by Indresh2410** [comment]
Thanks @mrueg . Have addressed it. Can you please check once?

**Pull request merged**
