### PR TITLE
[release-2.2] Backport #1610

### PR DESCRIPTION
**Pull request by ahmed-mez**
**What this PR does / why we need it**:

Backport https://github.com/kubernetes/kube-state-metrics/pull/1610

@dgrisonnet

### CODE REVIEW

**Comment by ahmed-mez** [comment]
@dgrisonnet @mrueg is there en ETA for 2.2.4 to release this fix? thanks!

**Comment by dgrisonnet** [comment]
I'll try to take some time tomorrow to cut it.

cc @fpetkovski for awareness

**Comment by dgrisonnet** [comment]
Seems like I still don't have the permissions https://github.com/kubernetes/org/pull/2955. I will try to have that PR merged by EOD, so the release would be either later today or on Monday. Sorry for the inconvenience.

**Pull request merged**
