### PR TITLE
Pushes go to staging-k8s.gcr.io

### PR DESCRIPTION
**Pull request by thockin**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kube-state-metrics/349)

### CODE REVIEW

**Comment by brancz** [comment]
I'm not a Google employee so I am not the one pushing the images to the gcr.io registry. Can you elaborate on the process images go through here until they end up in k8s.gcr.io? My guess they go through some sort of review and or security scan, but where is this documented?

**Comment by andyxning** [comment]
@thockin What is the difference between `k8s.gcr.io` and `staging-k8s.gcr.io`. And why should we move to `staging-k8s.gcr.io`.

**Comment by thockin** [comment]
https://github.com/kubernetes/kubernetes/pull/57824

TL;DR:

* The new staging-k8s.gcr.io is where we push images. It is literally
an alias to gcr.io/google_containers (the existing repo) and is hosted
in the US.
* The contents of staging-k8s.gcr.io are automatically synced to
{asia,eu,us)-k8s.gcr.io.
* The new k8s.gcr.io will be a read-only alias to whichever regional
repo is closest to you.
* In the future, images will be promoted from staging to regional
"prod" more explicitly and auditably.

**Comment by brancz** [comment]
Perfect! Thanks for the explanation!

**Pull request merged**
