### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by ekrecker**
I've fixed some typos

### CODE REVIEW

**Comment by lilic** [comment]
Thanks for your contribution! Do you mind just singing the CLA and then we can merge, see details in this comment -> https://github.com/kubernetes/kube-state-metrics/pull/1283#issuecomment-717236386

**Comment by ekrecker** [comment]
I create Linux Foundation ID.
Is there anything I have to do ?

**Comment by lilic** [comment]
@ekrecker make sure you use same email in your commit and github as you did when singing the CLA, rest of the instruction are here https://github.com/kubernetes/community/blob/master/CLA.md#the-contributor-license-agreement

**Comment by ekrecker** [comment]
I did not noticed "HelloSign" mail, so signed CLA.
I make sure the e-mail.

**Review by lilic — COMMENTED** [review]
Thanks!
/lgtm

**Comment by ekrecker** [comment]
@lilic
I've signed CLA so `cncf-cla` has changed to yes.

**Pull request merged**
