### PR TITLE
Add rexagod as reviewer

### PR DESCRIPTION
**Pull request by dgrisonnet**
Thank you for all the efforts you've been putting into kube-state-metrics and welcome to the team! :tada: 

/assign @mrueg @fpetkovski 
/cc @logicalhan @rexagod

### CODE REVIEW

**Comment by dgrisonnet** [comment]
Looks like we should wait for https://github.com/kubernetes/org/issues/3830 to merge

**Comment by fpetkovski** [comment]
Thank you for all of your contributions 🎉 

/lgtm
/hold

**Comment by rexagod** [comment]
It's an honor to get to be a part of the team! Thank you Damien, Filip, Manuel, and Han for maintaining such a welcoming air around this project, making it easy for folks like me to contribute! I'll try my best to live up to this role! 🎉

**Comment by mrueg** [comment]
/lgtm 

Thanks for your contributions @rexagod! Looking forward to improving kube-state-metrics together with you :)

**Comment by rexagod** [comment]
/verify-owners
https://github.com/kubernetes/org/pull/3849 was merged.

**Pull request merged**
