### PR TITLE
bump versions of prometheus,kubernetes, and addon-resizer

### LINKED ISSUE #706: kube-static-metrics addon-resizer error
ERROR: logging before flag.Parse: I0326 14:44:55.136801       1 pod_nanny.go:81] Watching namespace: kube-system, pod: kube-state-metrics-65f9c6fcdf-gcbrm, container: kube-state-metrics.
ERROR: logging before flag.Parse: I0326 14:44:55.136808       1 pod_nanny.go:82] storage: MISSING, extra_storage: 0Gi
ERROR: logging before flag.Parse: I0326 14:44:55.138236       1 pod_nanny.go:171] Failed to read data from config file "MISSING/NannyConfiguration": open MISSING/NannyConfiguration: no such file or directory, using default parameters
ERROR: logging before flag.Parse: I0326 14:44:55.138294       1 pod_nanny.go:109] cpu: 100m, extra_cpu: 1m, memory: 100Mi, extra_memory: 2Mi
ERROR: logging before flag.Parse: I0326 14:44:55.138315       1 pod_nanny.go:138] Resources: [{Base:{i:{value:100 scale:-3} d:{Dec:<nil>} s:100m Format:DecimalSI} ExtraPerNode:{i:{value:1 scale:-3} d:{Dec:<nil>} s:1m Format:DecimalSI} Name:cpu} {Base:{i:{value:104857600 scale:0} d:{Dec:<nil>} s:100Mi Format:BinarySI} ExtraPerNode:{i:{value:2097152 scale:0} d:{Dec:<nil>} s:2Mi Format:BinarySI} Name:memory}]

kubernetes 1.13.3
addon-resizer:1.8.3

### PR DESCRIPTION
**Pull request by tariq1890**
Updating some dependencies.

This should also partly fix #706 .

### CODE REVIEW

**Comment by mxinden** [comment]
/approve
/lgtm
/hold

In case this is a bug fix and you would like it to be included in the _v1.6.0_ release, this pull request should target the _release-1.6_ branch.

**Comment by brancz** [comment]
If I understand #706 correctly this should indeed be in 1.6.

**Comment by tariq1890** [comment]
I edited the target branch. I'll leave this for you to decide whether it should be merged or not @mxinden @brancz since the next rc has already been created.

**Comment by brancz** [comment]
I'd say let's cut another rc, it doesn't hurt.

**Comment by tariq1890** [comment]
Alright. This will be the last of my PRs. I'll continue the rest after release-1.6 finally goes through.

@mxinden Thoughts on creating a new RC for this? Sorry if this is a bother.

**Comment by mxinden** [comment]
/hold cancel

No worries. I will cut another release candidate.

**Pull request merged**
