### PR TITLE
internal/store/builder.go: Fix K8s API version

### PR DESCRIPTION
**Pull request by mjura**
(cherry picked from commit 7e6ee51012887301e9f62836566ecd1c18a146c9)

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes # https://github.com/kubernetes/kube-state-metrics/issues/1039

### CODE REVIEW

**Comment by brancz** [comment]
Thanks!

**Comment by LiliC** [comment]
Thanks!

We also need to do a release for this, @brancz do you mind taking care of that? Thanks!

**Comment by brancz** [comment]
I can yes. I think #1042 and this warrant a new release.

**Pull request merged**
