### PR TITLE
Bump client-go and friends to v0.20 (kubernetes v1.20)

### PR DESCRIPTION
**Pull request by lilic**
Bumping all the things to k8s v1.20.

cc @brancz @tariq1890 PTAL, thanks!

### CODE REVIEW

**Comment by lilic** [comment]
Doing it towards the release-2.0 branch and will bring then to master as well. I thought would be good to have this release be up to date with v1.20.

**Comment by tariq1890** [comment]
Any reason why we revendored? I may have missed some previous discussion I think

**Comment by lilic** [comment]
@tariq1890 this is the 2.0 branch, the removal of the vendor directory only happened in master. Unless you are referring to something else?

**Review by brancz — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
