### PR TITLE
add secret and configmap metrics

### LINKED ISSUE #370: Is there any metrics about configmaps and secrets ?
Hello,

I'm looking for the way to monitoring configmaps and secrets changes. Is there any thing like this in kube-state-metrics ? If not do you know if there is a way to have it ?

The goal of this task is to be able to detect any changes made on some critical configmap or secret used by my pods.

Regards

### PR DESCRIPTION
**Pull request by andyxning**
Fix #370

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kube-state-metrics/379)

### CODE REVIEW

**Comment by andyxning** [comment]
/cc @brancz 
Ping @younid

**Comment by brancz** [comment]
I think @younid also needed something like an updated at timestamp for alerting purposes, any chance we can get something like that?

**Comment by andyxning** [comment]
@brancz I have wrongly thought that the `generation` will be updated every time secret is updated. But it is wrong. I have checked that there are no update time in object metadata in Kubernetes object. But According to the doc, we can use `ResourceVersion` as the update indicator. :)

> 		// An opaque value that represents the internal version of this object that can
	// be used by clients to determine when objects have changed. May be used for optimistic
	// concurrency, change detection, and the watch operation on a resource or set of resources.
	// Clients must treat these values as opaque and passed unmodified back to the server.
	// They may only be valid for a particular resource or set of resources.
	//
	// Populated by the system.
	// Read-only.
	// Value must be treated as opaque by clients and .
	// More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#concurrency-control-and-consistency
	// +optional
	ResourceVersion string `json:"resourceVersion,omitempty" protobuf:"bytes,6,opt,name=resourceVersion"`

I have updated `generation` metrics to `resoruce_version`. PTAL.

**Comment by pdecat** [comment]
This requires new permissions to be declared on the cluster role at https://github.com/kubernetes/kube-state-metrics/blob/master/kubernetes/kube-state-metrics-cluster-role.yaml#L9

**Pull request merged**
