### PR TITLE
chore: Sync `release-2.11`

### PR DESCRIPTION
**Pull request by rexagod**
Sync `release-2.11` with `main` (to be merged once that's in). A comparison between `main`-rebased-`release-2.11` and `release-2.11` is available can be seen [here](https://github.com/rexagod/kube-state-metrics/compare/rexagod:kube-state-metrics:release-2.11...release-2.11-sync) to visualize any additional conflicts (or commits) we'll see while syncing.

***

- [ ] Blocked by https://github.com/kubernetes/kube-state-metrics/pull/2317 and https://github.com/kubernetes/kube-state-metrics/pull/2316. Please merge them first.
- [ ] Raise a `kpromo` PR to `k8s.io` for the newer release once it's out.

### CODE REVIEW

**Comment by djsly** [comment]
should we expect 2.11 release soon now the the Chore item was merged ?

**Comment by rexagod** [comment]
@djsly `v2.11` is out now. :)

**Comment by djsly** [comment]
awesome! should we expect the docker image and chart to be updated by end of week ?

**Comment by rexagod** [comment]
ACK, once https://github.com/kubernetes/k8s.io/pull/6573 is in.

**Pull request merged**
