### PR TITLE
adding the CI check for go modules consistency

### PR DESCRIPTION
**Pull request by tariq1890**
Updated Travis CI to check for go mod consistency.

### CODE REVIEW

**Comment by brancz** [comment]
Let’s also add a “go mod verify”

Otherwise lgtm

**Comment by tariq1890** [comment]
@brancz added!

**Comment by brancz** [comment]
Good catch @mxinden. Then we should be good to go.

**Comment by tariq1890** [comment]
Thanks for pointing that out @mxinden !

**Comment by brancz** [comment]
Awesome! Thank you!

/lgtm
/approve

**Pull request merged**
