### PR TITLE
use new promlint package and bump prometheus cli

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

Update Prometheus CLI to 2.28.1
Make use of `github.com/prometheus/client_golang/prometheus/testutil/promlint` instead of `github.com/prometheus/prometheus/util/promlint` and drop the dependency `github.com/prometheus/prometheus`.

Dropping the dependency `github.com/prometheus/prometheus` helps to re-use kube-state-metric packages because the dependency lead to import it transitively by go modules.

<sup>
Christian Schlotter <christian.schlotter@daimler.com>, Daimler TSS GmbH, 
<a href="https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md">Imprint</a>
</sup>

### CODE REVIEW

**Comment by fpetkovski** [comment]
great stuff, lgtm

**Comment by mrueg** [comment]
@chrischdi Thanks for your contribution!

**Pull request merged**
