### PR TITLE
add job owner info in kube_job_info

### PR DESCRIPTION
**Pull request by zouyee**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kube-state-metrics/231)

### CODE REVIEW

**Comment by brancz** [comment]
Since we're deprecating the created by labels elsewhere, shouldn't we just add metrics for owner references?

**Comment by zouyee** [comment]
I forget it...

**Comment by andyxning** [comment]
@zouyee 

I have found nothing info about ownerReference for cronjob in the provided url. Could you please add more info for this.

**Comment by andyxning** [comment]
According to [gc doc](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#owners-and-dependents), it does not state that jobs created by cronjob will have `ownerreference` to cronjob. 

I have test this with minikube on Kubernetes 1.7.2 and it indeed does not have a `ownerreference` to the cronjob.

Maybe this should first be added in Kubernetes and then collect them in kube-state-metrics.

**Comment by brancz** [comment]
As all of Kubernetes is moving away from the created-by annotations I don't think we should introduce them to begin with, it's just something people will get upset by when we deprecate it shortly after it was introduced.

**Comment by andyxning** [comment]
Yes. That is why i suggest we should first add `ownerreference` to jobs in Kubernetes. After created by annotation is deprecated, we can still use the `ownerreference` to accomplish the same job as what created by annotation does. :)

**Comment by brancz** [comment]
Sorry, I wasn't very clear in my previous comment, I meant to say that I agree with you @andyxning . :slightly_smiling_face:

**Comment by zouyee** [comment]
In my opinion，according to [owenreference](https://github.com/kubernetes/kubernetes.github.io/blob/490fb99a307d808ead693123d0fbccdb6286f247/docs/concepts/workloads/controllers/garbage-collection.md),kubernetes would not add ownerreference for cronjob dynamically, it would be suitable to using annotation before deprecated

**Comment by andyxning** [comment]
@zouyee Could you please detail the reason about why kubernetes will not add ownerreference for jobs created by cronjob.

**Comment by zouyee** [comment]
according to this processing listhttps://github.com/kubernetes/community/blob/master/contributors/design-proposals/controller-ref.md#implementation

**Comment by brancz** [comment]
With CronJobs being the only consumer/possible owner of Job objects, do you think it's worth generating 3+ extra metrics for every job?

**Pull request closed without merging**
