### PR TITLE
Merge performance optimization into master

### PR DESCRIPTION
**Pull request by mxinden**
**What this PR does / why we need it**:

Given that all collectors are now updated to the new performance optimized architecture, we can go ahead and merge the optimizations into master. What do you all think?

This is rebased onto current master to get rid of the merge commits and the thereby implied CLA issues. For more info see https://github.com/kubernetes/kube-state-metrics/pull/599.

### CODE REVIEW

**Comment by brancz** [comment]
Ok, 3rd time's the charm. This has been a long time coming, congrats on all the great work! :tada: 

/lgtm

**Comment by mxinden** [comment]
> Ok, 3rd time's the charm. This has been a long time coming, congrats on all the great work! tada

Merci. I can prepare the changelog for the alpha release next. What do you think @brancz?

**Comment by brancz** [comment]
@mxinden sounds perfect.

**Comment by mxinden** [comment]
@brancz would you mind deleting the `performance-optimization*` branches on the upstream repo?

**Comment by brancz** [comment]
Thanks for the reminder. Done.

**Pull request merged**
