### PR TITLE
.travis.yaml: Add job names

### PR DESCRIPTION
**Pull request by LiliC**
**What this PR does / why we need it**:

Adding the names of the jobs makes it easier to spot which jobs failed.

### CODE REVIEW

**Comment by brancz** [comment]
for some reason this makes travis not run them in parallel, hence why they weren't named before

**Comment by tariq1890** [comment]
Then it should be reported to the Travis peeps IMO. Having Job names is useful. Hopefully, we can revisit this later.

**Comment by brancz** [comment]
We have to migrate away from travis unfortunately anyways as it stopped working with prow ...

**Comment by brancz** [comment]
IIRC this was intended behavior

**Comment by andyxning** [comment]
We can not see any travis ci output for this PR. Adding names to each stage is definitely more readable. reopen this to do a further diagnose.

/reopen

**Comment by andyxning** [comment]
Seems the branch has been deleted. :(

**Pull request closed without merging**
