### PR TITLE
bump kubernetes to 1.8

### PR DESCRIPTION
**Pull request by andyxning**
This PR update kubernetes dependencies to 1.8.

/cc @brancz @zouyee

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kube-state-metrics/269)

### CODE REVIEW

**Comment by brancz** [comment]
lgtm, thanks for taking care of this!

**Comment by andyxning** [comment]
Have test this PR with Kubernetes 1.6. Everything seems ok.

Also, based on [comment](https://github.com/kubernetes/kube-state-metrics/pull/269#issuecomment-335782131) above.

Will merge this once the CI is green.

**Comment by brancz** [comment]
If we're not comfortable with directly releasing stable 1.1.0, I'm perfectly fine with cutting an RC first.

**Comment by andyxning** [comment]
Yes. A rc release is preferable. 

Will do.

**Pull request merged**
