### PR TITLE
Add Metrics About StorageClass

### LINKED ISSUE #775: storageclass metrics can be supported?
kube-state-metrics not supported cluster's resource: storageclass,will you support it later?

### PR DESCRIPTION
**Pull request by xieyanker**
**What this PR does / why we need it**:

Add Some Metrics About StorageClass

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #775

### CODE REVIEW

**Comment by xieyanker** [comment]
I signed it

**Comment by xieyanker** [comment]
> 谢谢你的拉动请求。在我们查看您的请求之前，您需要签署“贡献者许可协议”（CLA）。
> 
> 📝 **请按照https://git.k8s.io/community/CLA.md#the-contributor-license-agreement上的说明签署CLA。**
> 
> CLA签名可能需要几分钟才能完全注册; 之后，请在这里回复一个新的评论，我们将验证。谢谢。
> 
> * 如果您已经签署了CLA，我们可能没有您的GitHub用户名，或者您使用的是其他电子邮件地址。检查您现有的CLA数据，并验证您的[电子邮件是否已在您的git提交中设置](https://help.github.com/articles/setting-your-email-in-git/)。
> * 如果您作为公司签署了CLA，请使用您组织的凭据登录https://identity.linuxfoundation.org/projects/cncf进行授权。
> * 如果您已完成上述操作并仍然遇到CLA报告为未签名的问题，请使用Linux Foundation帮助台记录一张票：[https](https://support.linuxfoundation.org/)：[//support.linuxfoundation.org/](https://support.linuxfoundation.org/)
> * 如果您遇到Linux Foundation Helpdesk的任何问题，请发送邮件至备份电子邮件支持地址：[login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)

I signed it

**Comment by tariq1890** [comment]
@xieyanker can you check if your CNCF registered email address matches your email associated with the commits?

**Comment by xieyanker** [comment]
> @xieyanker can you check if your CNCF registered email address matches your email associated with the commits?

thank you,my commit account is wrong,and I create a pull request once more: https://github.com/kubernetes/kube-state-metrics/pull/777

**Pull request closed without merging**
