### PR TITLE
Bump to go 1.18.2, k8s 1.24, kind 0.14.0, prometheus 2.35.0

### PR DESCRIPTION
**Pull request by mrueg**
**What this PR does / why we need it**:
Bumps necessary tooling in preparation for a 2.5.x release
**How does this change affect the cardinality of KSM**: *(increases, decreases or does not change cardinality)*

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

Please do not merge yet, this is to test that the linting change is working successfully.

### CODE REVIEW

**Comment by fpetkovski** [comment]
Looks like the go-lint job started to fail. Will this PR fix that?

**Comment by fpetkovski** [comment]
/lgtm
/hold

Is this safe to merge now? If so, feel free to remove the hold :)

**Comment by mrueg** [comment]
> /lgtm /hold
> 
> Is this safe to merge now? If so, feel free to remove the hold :)

Yes it's safe now.
I repushed another change to address https://github.com/advisories/GHSA-hp87-p4gw-j4gq 

Can you lgtm again?

/hold cancel

**Pull request merged**
