### PR TITLE
*: cut 0.6.0

### PR DESCRIPTION
**Pull request by fabxc**
@alamaison

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kube-state-metrics/170)

### CODE REVIEW

**Comment by brancz** [comment]
I guess it doesn't hurt us to do a v0.6.0 release before the GA. I still have to catch up a bit from vacation, but generally I'm ok with this.

**Comment by samuelmanzer** [comment]
Yes pls :) Very excited to use Job/CronJob metrics that were added since last release

**Comment by 2rs2ts** [comment]
I would love a release ASAP so I can get #175 without having to build this project myself :)

**Comment by brancz** [comment]
Google is currently performing scalability tests, so we might skip 0.6 and go to 1.0 directly as the results are looking pretty good. We'll have an update soon!

https://github.com/kubernetes/kube-state-metrics/issues/124#issuecomment-318394185

**Comment by 2rs2ts** [comment]
What would be the minimum ETA for a hypothetical 0.6 versus 1.0?

**Comment by brancz** [comment]
This PR is outdated so I'll close it here. We're still trying to figure out how to go 1.0/GA. I'm trying to resolve this and get a new release out as soon as I can. Hang in there! :slightly_smiling_face:

**Pull request closed without merging**
