### PR TITLE
Release 1.3

### LINKED ISSUE #443: Is v1.3.1 officially released?
Hey 👋 

I am fairly enjoying this image released on `https://quay.io/repository/coreos/kube-state-metrics?tag=latest&tab=tags`, thank you very much! I wondered if version 1.3.1 is officially released, because it is not tagged as `latest` in the image repo and not declared as latest version in the `latest version` section of the readme. If it is officially released, would it be possible to also tag the v1.3.1 as latest? This would be awesome!

Thanks :)

### PR DESCRIPTION
**Pull request by brancz**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #443

### CODE REVIEW

**Comment by andyxning** [comment]
@brancz This should be rebased and adjusted. :)

**Comment by brancz** [comment]
I'm knee deep in other things, so if you have time, I'd appreciate if you can pick this up. Otherwise I'll get back to it in the upcoming weeks.

**Comment by andyxning** [comment]
Will give it a try recently. :)

**Comment by zouyee** [comment]
cla?

**Pull request closed without merging**
