### PR TITLE
Cut v1.4.0-rc.0

### PR DESCRIPTION
**Pull request by brancz**
Assuming everything goes well, we will be aiming for Monday the 13th of August for the stable 1.4.0 release. I encourage everyone to test this so we can find bugs, should there be any new ones introduced.

/assign @andyxning 

@piosz @loburm please stand by to push the container images to gcr.io once this is merged.

### CODE REVIEW

**Comment by brancz** [comment]
cc @zouyee :slightly_smiling_face:

**Comment by andyxning** [comment]
Sorry for the late.
/lgtm

**Comment by andyxning** [comment]
Please add a comment once the new image has been pushed to quay.io and gcr.io.
@brancz @loburm @piosz

**Comment by loburm** [comment]
@andyxning should I build it from head or wait for official release and tag?

**Comment by zouyee** [comment]
@andyxning create  `v1.4.0-rc.0` tag ?

**Comment by andyxning** [comment]
> should I build it from head or wait for official release and tag?

@loburm Please wait for @brancz cut the v1.4.0-rc.0 tag.

**Comment by brancz** [comment]
Sorry for all the delay, last week was PromCon and I was insanely busy. I just pushed the release tag and will also push the quay image.

**Comment by brancz** [comment]
I pushed the git tag and container image and created the release. Sorry for the trouble. Should everything go well I would say we aim for next week Monday for the final release.

**Comment by loburm** [comment]
I have pushed images to staging env. 
staging-k8s.gcr.io/kube-state-metrics-amd64:v1.4.0-rc.0

Do we need to have release candidates in the main registry?

**Comment by loburm** [comment]
Actually it's already written that kube-state-metrics images are going to staging:
https://github.com/kubernetes/kube-state-metrics/blob/master/RELEASE.md

Maybe we should update that it's related only to release candidates, but normal released images should go to main repo?

**Comment by brancz** [comment]
Yeah, also I think the majority of people refer to this: https://github.com/kubernetes/kube-state-metrics#container-image

**Comment by loburm** [comment]
Done:
https://github.com/kubernetes/kube-state-metrics/pull/509

I'm not updating README page, because it has links only to latest tested releases.

**Pull request merged**
