### PR TITLE
chore: Fix the security issue about sirupsen/logrus

### PR DESCRIPTION
**Pull request by kevinwangcn**
There is a security concern using the `github.com/sirupsen/logrus` with version `1.8.1`

**Supporting Material/References:**
https://github.com/sirupsen/logrus/issues/1370

**Impact**
This happens if you try to log something that is longer than 64kb without newlines through something like cmd.Stdout = logrus.Writer().
This can cause a denial of service in some cases.

**What this PR does / why we need it**:
The PR is going to bump up the version for this particular module from `1.8.1` to `1.9.3` which has resolved the security issue. 

**How does this change affect the cardinality of KSM**: *(increases, decreases or does not change cardinality)*

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by CatherineF-dev** [comment]
Can you use `go get github.com/sirupsen/logrus@v1.9.3` instead of replace?

**Comment by kevinwangcn** [comment]
> Can you use `go get github.com/sirupsen/logrus@v1.9.3` instead of replace?

Updated my PR. thanks for the review.

**Comment by rexagod** [comment]
Is there a CVE for this vulnerability? Does golvulncheck validate that the affected symbols are actually being used in the codebase?

**Comment by kevinwangcn** [comment]
> Is there a CVE for this vulnerability? Does golvulncheck validate that the affected symbols are actually being used in the codebase?

yes, this is going to solve a CVE issue. Attached is the scan report via Twistlock.  Please refer to it for more details.
[scan-result.csv](https://github.com/user-attachments/files/17121821/scan-result.csv)

**Comment by kevinwangcn** [comment]
@rexagod  @CatherineF-dev  Could you please review my PR? Thanks a lot.

**Pull request merged**
