### PR TITLE
Rm code_of_conduct.md

### PR DESCRIPTION
**Pull request by zouyee**
Remove `code_of_conduct.md` for the duplication of `code-of-conduct.md`.
/cc @brancz 

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kube-state-metrics/325)

### CODE REVIEW

**Comment by andyxning** [comment]
What @spiffxp done in #322 is somewhat a standard for all the repos under Kubernetes Org. Let's keep the consistency by keeping `code-of-conduct.md` and removing `code_of_conduct.md`.

**Comment by brancz** [comment]
Agreed.

**Comment by zouyee** [comment]
done!

**Comment by spiffxp** [comment]
thanks for the catch!

**Pull request merged**
