### PR TITLE
gofmt

### PR DESCRIPTION
**Pull request by asifdxtreme**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kube-state-metrics/206)

### CODE REVIEW

**Comment by brancz** [comment]
gofmt should not be run on the vendor directory, aside from that, do you maybe want to setup running gofmt on every run on travis? That way we don't have to make sure ourselves.

**Comment by andyxning** [comment]
Maybe we should add another stage `Fmt code` in travis CI.

**Comment by asifdxtreme** [comment]
@brancz @andyxning  yes adding this check in travis CI will be better so that non-formatted code does not pass the check, Thanks for your suggestion, I will add this check in travis conf

**Comment by asifdxtreme** [comment]
Raised a new PR with the suggested changes https://github.com/kubernetes/kube-state-metrics/pull/210

**Pull request closed without merging**
