### PR TITLE
*: Cut v2.2.0 release

### PR DESCRIPTION
**Pull request by mrueg**
* [FEATURE] Add --use-apiserver-cache flag to set resourceVersion=0 for ListWatch requests #1548
* [FEATURE] Introduce metrics for Kubernetes object annotations #1468
* [FEATURE] Introduce start time metric for containers in terminated state #1519
* [FEATURE] Introduce metrics for cronjob job history limits #1535
* [FEATURE] Add system_uuid dimension to kube_node_info metric #1535
* [FEATURE] Add available replica metric for statefulsets #1532
* [FEATURE] Add ready replica metric for deployments #1534
* [CHANGE]  Update go clients for Kubernetes to support 1.22 #1545
* [CHANGE]  Use new promlint package and update prometheus cli to 2.28.1 #1531

**What this PR does / why we need it**:

**How does this change affect the cardinality of KSM**: *(increases, decreases or does not change cardinality)*

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by brancz** [comment]
/lgtm
/approve
/hold

Feel free to remove hold whenever you are ready to move ahead :)

**Review by dgrisonnet — APPROVED** [review]
/lgtm

**Review by lilic — APPROVED** [review]
Thanks!

/lgtm

**Pull request merged**
