### PR TITLE
docs: Update Services, Pods, Nodes with Description and Unit

### LINKED ISSUE #1356: More information requested in the documentation for metrics
**What would you like to be added**:

It would be helpful if the metrics had a description and a unit associated to in their documentation like in the cadvisor documentation shown here https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md.  I'll specifically need it for Node Metrics, Pod Metrics, and Service Metrics.

**Why is this needed**:

To better understand the metrics themselves

**Describe the solution you'd like**

For example with looking at https://github.com/kubernetes/kube-state-metrics/blob/master/docs/node-metrics.md it would be nice if a description and base unit columns were added.

Most of the metrics don't have a base unit, but at the least a description would be very helpful.

### PR DESCRIPTION
**Pull request by JESWINKNINAN**
What this PR does / why we need it:
This PR will give users more information on metrics under Services, Nodes, Pods.

Which issue(s) this PR fixes:
Fixes #1356

### CODE REVIEW

**Review by lilic — COMMENTED** [review]
Thanks this looks like what we want! Was this generated, if so can you commit the way you generated so we can reuse it? Thanks!

**Comment by JESWINKNINAN** [comment]
@lilic As discussed, I have done this manually. Can we have a follow-up task to automate the process.

**Comment by JESWINKNINAN** [comment]
> Thanks this looks like what we want! Was this generated, if so can you commit the way you generated so we can reuse it? Thanks!

**Review by lilic — COMMENTED** [review]
Thanks!

We can merge this, do you mind just squashing the commits into one? After that we can merge 🎉 Thanks again!

As a follow-up lets open an issue afterwards to add two things:
1. issue for validation - makes sure this is up to date when changes are made on metrics.
2. issue for automation for all metrics docs - write a script that generates the docs files.

Let me know if you want to open the issues, otherwise I can do it. Contributions on those welcome as well! 🎉

**Comment by JESWINKNINAN** [comment]
> Thanks!
> 
> We can merge this, do you mind just squashing the commits into one? After that we can merge 🎉 Thanks again!
> 
> As a follow-up lets open an issue afterwards to add two things:
> 
> 1. issue for validation - makes sure this is up to date when changes are made on metrics.
> 2. issue for automation for all metrics docs - write a script that generates the docs files.
> 
> Let me know if you want to open the issues, otherwise I can do it. Contributions on those welcome as well! 🎉

Sure @lilic I will squash the commits and will let you know. It will be good if you have follow-up stories as issues opened and assigned to me. Thanks.

**Comment by JESWINKNINAN** [comment]
@lilic I have squashed the commits as mentioned, can you please review

**Review by lilic — COMMENTED** [review]
/lgtm

thank you for your contribution 🎉

**Pull request merged**
