### PR TITLE
fix service label to match deployment pod label

### PR DESCRIPTION
**Pull request by padolan**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kube-state-metrics/94)

### CODE REVIEW

**Comment by fabxc** [comment]
Thanks. That's a correct fix of course.
Now the only question is whether it should be fixed like this or by making the deployment have the label `k8s-app`. I like to think that kube-state-metrics should be part of every production cluster and thus is an `k8s-app`, but more opinions on this would help.

@brancz 

@piosz do you know more on whether there's a clear definition on what falls under "k8s-app"?

**Comment by piosz** [comment]
I don't know. We had similar discussion here https://github.com/kubernetes/contrib/pull/2420#discussion_r103153127.

@bgrant0607 what is the semantic/policy behind `k8s-app`?

**Comment by brancz** [comment]
I agree with rather changing the label in the deployment manifest, as @fabxc mentioned kube-state-metrics is a cluster component.

@fabxc @piosz if it turns out there is no semantic/policy in place I think this one is worth formalizing.

**Comment by bgrant0607** [comment]
@piosz Add-ons in the kube-system namespace use the k8s-app label key.

https://github.com/kubernetes/kubernetes/search?p=2&q=k8s-app&utf8=%E2%9C%93

**Comment by piosz** [comment]
This is the current state. The question is whether it's the standard?

**Comment by brancz** [comment]
#98 instead fixed the `Pod`'s label from `app` to `k8s-app` so it matches the `Service` object. As discussed, kube-state-metrics is a cluster add-on that is aimed to reach a stable state for the 1.7 release. Being a cluster add-on justifies the label to be `k8s-app` instead of `app`. Therefore closing this in favor of #98.

**Pull request closed without merging**
