### PR TITLE
build: Build with go 1.20.1

### PR DESCRIPTION
**Pull request by mrueg**
**What this PR does / why we need it**:
Bumps to go 1.20.x
Also bump prometheus and golangci-lint

**How does this change affect the cardinality of KSM**: *(increases, decreases or does not change cardinality)*
None
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by mrueg** [comment]
@dgrisonnet can you take a look if you got some spare cycles?

**Comment by mrueg** [comment]
@dgrisonnet it's rebased now

**Review by dgrisonnet — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
