### PR TITLE
internal/store/: Remove hpa metric kube_hpa_status_current_metrics_av…

### PR DESCRIPTION
**Pull request by LiliC**
…erage_value

due to unhandled edge cases and precision loss. Because we are not
handling nil cases correctly we often experience segfault in various edge
case scenarios.

cc @tariq1890 @brancz

### CODE REVIEW

**Comment by brancz** [comment]
Looks like the metric wasn't entirely removed, as documentation CI failed expecting it to be documented.

**Comment by LiliC** [comment]
@brancz PTAL thanks!

**Comment by LiliC** [comment]
@brancz PTAL, thanks!

**Comment by tariq1890** [comment]
Thanks @LiliC !

**Pull request merged**
