### PR TITLE
add LiLiC as approver

### PR DESCRIPTION
**Pull request by tariq1890**
@LiliC has been contributing to the kube-state-metrics project since a long time. With all of her quality contributions, invaluable improvements to the CI processes and participations in several PR reviews, it's only fitting that we add her to the team.

Welcome @LiliC !

### CODE REVIEW

**Comment by brancz** [comment]
> The following users are mentioned in OWNERS file(s) but are not members of the kubernetes org.

Time to propose you to the org :)

**Comment by tariq1890** [comment]
@andyxning I believe @LiLiC has to accept the K8s org invite.

**Comment by LiliC** [comment]
I accepted it, should be good to go now :) Thanks all!

**Comment by andyxning** [comment]
Welcome @LiliC !

**Comment by LiliC** [comment]
Thanks @andyxning :) 🎉

**Pull request merged**
