### PR TITLE
*: Cut v1.7.1

### PR DESCRIPTION
**Pull request by tariq1890**
Includes the following two fixes:

#831 #832

### CODE REVIEW

**Comment by tariq1890** [comment]
@loburm @piosz Requesting gcr images to be built and pushed for v1.7.1.

**Comment by loburm** [comment]
I think we should somehow change release process. I can't push new gcr image, because there is no 1.7.1 tag. And I assume you don't want to create new tag, because we don't have yet the image?

**Comment by tariq1890** [comment]
@LiliC Perhaps it's the latter.

@loburm We are definitely open to making changes.

**Pull request merged**
