### PR TITLE
Promote v2.0.0 to beta pre-release

### PR DESCRIPTION
**Pull request by lilic**
🎉  There were no bug reports around the functionality of the latest alpha releases, so we can now safely promote v2.0.0 to beta.

Next are scale and performance tests. If no major regressions are found, and no new bugs I would say we can cut a rc of v2.0.0. Unless any objections?

cc @brancz @tariq1890

### CODE REVIEW

**Review by brancz — APPROVED** [review]
Let's do this! :tada:

**Comment by lilic** [comment]
Note we had one change since the last release but was not affecting users, not sure changing default image in examples makes sense to point out?

**Comment by lilic** [comment]
@brancz I need an lgtm label :D

**Comment by lilic** [comment]
@brancz I had to make some adjustments to our e2e tests due to recent changes in default image in examples, see last commit. PTAL, thanks!

**Pull request merged**
