### PR TITLE
refactor to toward kubernetes way

### PR DESCRIPTION
**Pull request by andyxning**
This PR will refactor kube-state-metrics to be a more kubernetes way. Mainly:
* move `collectors`/`version` packages under `pkg` package
* refactor flag command arguments configuration to `options` package

### CODE REVIEW

**Comment by brancz** [comment]
lgtm on green

**Comment by andyxning** [comment]
Ping @brancz

**Comment by HackerWilson** [comment]
@andyxning 
when assign args to `--collectors`, there would be a panic:
```
panic: assignment to entry in nil map

goroutine 1 [running]:
k8s.io/kube-state-metrics/pkg/options.CollectorSet.Set(0x0, 0x7ffeefbffa77, 0x4, 0x20, 0x1bfc1a0)
	/Users/wen/HackerWilson/go/src/k8s.io/kube-state-metrics/pkg/options/types.go:48 +0x1a1
k8s.io/kube-state-metrics/vendor/github.com/spf13/pflag.(*FlagSet).setFlag(0xc420106870, 0xc4201bf2c0, 0x7ffeefbffa77, 0x4, 0x7ffeefbffa6a, 0x11, 0x7ffeefbffa6c, 0xc420163c00)
	/Users/wen/HackerWilson/go/src/k8s.io/kube-state-metrics/vendor/github.com/spf13/pflag/flag.go:802 +0x63
k8s.io/kube-state-metrics/vendor/github.com/spf13/pflag.(*FlagSet).Parse.func1(0xc4201bf2c0, 0x7ffeefbffa77, 0x4, 0x7ffeefbffa6a, 0x11, 0xc42021fa01, 0x2)
	/Users/wen/HackerWilson/go/src/k8s.io/kube-state-metrics/vendor/github.com/spf13/pflag/flag.go:960 +0x5c
k8s.io/kube-state-metrics/vendor/github.com/spf13/pflag.(*FlagSet).parseLongArg(0xc420106870, 0x7ffeefbffa6a, 0x11, 0xc4200b40b0, 0x0, 0x0, 0xc4203504f0, 0xc4200b40b0, 0x1, 0x1, ...)
	/Users/wen/HackerWilson/go/src/k8s.io/kube-state-metrics/vendor/github.com/spf13/pflag/flag.go:863 +0x2aa
k8s.io/kube-state-metrics/vendor/github.com/spf13/pflag.(*FlagSet).parseArgs(0xc420106870, 0xc4200b40b0, 0x0, 0x0, 0xc4203504f0, 0x3, 0x0)
	/Users/wen/HackerWilson/go/src/k8s.io/kube-state-metrics/vendor/github.com/spf13/pflag/flag.go:940 +0x48c
k8s.io/kube-state-metrics/vendor/github.com/spf13/pflag.(*FlagSet).Parse(0xc420106870, 0xc4200b4090, 0x3, 0x3, 0x1cb47e0, 0x25d8d20)
	/Users/wen/HackerWilson/go/src/k8s.io/kube-state-metrics/vendor/github.com/spf13/pflag/flag.go:963 +0xe5
k8s.io/kube-state-metrics/pkg/options.(*options).Parse(0xc4201067e0, 0xc4201067e0, 0xc4202c5d40)
	/Users/wen/HackerWilson/go/src/k8s.io/kube-state-metrics/pkg/options/options.go:72 +0x56
main.main()
	/Users/wen/HackerWilson/go/src/k8s.io/kube-state-metrics/main.go:58 +0x63
exit status 2
```
due to this line
```
#48  s[col] = struct{}{}
```

**Comment by brancz** [comment]
@andyxning ^

**Comment by andyxning** [comment]
Oops. Will take a look at this asap. Thanks for pointing this out. @HackerWilson

**Pull request merged**
