### PR TITLE
Modify label(snake_case from camelCase) key in kube_storageclass_info…

### PR DESCRIPTION
**Pull request by ankitsinhaiiitg**
… in storageclass and it's unit test.

**What this PR does / why we need it**:
In metric kube_storageclass_info change label from camelCase to snake_case, as it is required in e2e testing and was mentioned that label must be in snake_case.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by tariq1890** [comment]
@ankitsinhaiiitg Thanks for your PR :). However, this is considered a breaking change and we can't incorporate this until the next major release of kube-state-metrics (2.0)

**Comment by ankitsinhaiiitg** [comment]
> @ankitsinhaiiitg Thanks for your PR :). However, this is considered a breaking change and we can't incorporate this until the next major release of kube-state-metrics (2.0)

Okay, no problem, I was working on another issue, when I tried to run e2e, I got this issue and added this.

**Comment by tariq1890** [comment]
You will need to use an older version of prometheus.

**Comment by ankitsinhaiiitg** [comment]
> You will need to use an older version of prometheus.

Okay, yeah that issue was coming because of promtool. I got it now thanks.

**Comment by tariq1890** [comment]
Promtool is bundled in prometheus.

**Pull request closed without merging**
