### PR TITLE
docs: --resources replaced with --collectors in the CLI

### PR DESCRIPTION
**Pull request by stigok**
This is related to #915

**What this PR does / why we need it**:
It corrects invalid arguments used in the docs.

### CODE REVIEW

**Comment by tariq1890** [comment]
Thanks @stigok!

**Comment by olivierlemasle** [comment]
@tariq1890 PR #1080 and its twin #915 made me look again at this PR...
It's should be the opposite, right? Collectors have been renamed to resources with #1006, and documentation had already been updated to reflect this change. This PR actually reverts documentation to the old name.

**Comment by tariq1890** [comment]
Oh yes, thanks so much for catching this mistake @olivierlemasle. I will make the corrections.

**Comment by stigok** [comment]
@olivierlemasle lol. Now I understand. git blame sent me here https://github.com/kubernetes/kube-state-metrics/pull/1006

So how did I come about creating this PR? It was indeed because `--resources` didn't work, but `--collectors` did. My confusion stems from you merging v2 changes into master without bumping version. It could be nice to put up a warning about master being used to builld v2 in the readme :)

**Comment by tariq1890** [comment]
@stigok That’s a fair ask. We should update the README about breaking changes in master

**Pull request merged**
