### PR TITLE
do not merge: testing security checks

### PR DESCRIPTION
**Pull request by rexagod**

### CODE REVIEW

**Comment by mrueg** [comment]
This should rather be a scheduled job and not something that is run on a PR base as it will break unrelated benign changes.

My personal opinion: these scanners in general are too noisy output right now for this project (we're effectively only using gcr.io/distroless/static container and golang).
If there's a need to have a scanner, we should look into something like https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck which only checks the code in path.

**Comment by mrueg** [comment]
As your PR title is do not merge, I'll add a 

/hold

**Comment by rexagod** [comment]
Closing this as this was only for visualization purposes of the changes introduced in #1878, all related changes will be pushed there.

**Pull request closed without merging**
