### PR TITLE
replace git describe with VERSION file for maintaining version tagging

### LINKED ISSUE #684: Make container/E2e tests are not referring to the latest image tag of kube-state-metrics
We are still extracting `v1.5.0-alpha` as the latest release version when running the `e2e` tests and `make container`

This is probably happening because `git describe --abbrev=0` returns the following
`v1.5.0-alpha.0`

We would need to push the latest tag `1.5.0` to the current master.

/cc @mxinden @brancz

### PR DESCRIPTION
**Pull request by tariq1890**
Fixes #684

### CODE REVIEW

**Comment by tariq1890** [comment]
@mxinden Do we need to fix that line too? I thought it was for retrieving the current branch name.

**Comment by mxinden** [comment]
Yes, my bad. Sorry about that (_feeling-ashamed-as-I-wrote-the-script_).

**Comment by brancz** [comment]
Thanks @tariq1890 !

/lgtm

**Pull request merged**
