### PR TITLE
fix: Remove FieldSelector from non-namespaced resources 

### LINKED ISSUE #2187: Argument namespaces-denylist produces an error with v2.10.0
**What happened**:

I upgraded kube-state-metrics from 2.9.2 to 2.10.0 on several clusters. On a single cluster it did not work as expected.

This is the error message I got there:
```
W0908 12:40:15.252401       1 reflector.go:533] pkg/mod/k8s.io/client-go@v0.27.5/tools/cache/reflector.go:231: failed to list *v1.Node: field label not supported: metadata.namespace
E0908 12:40:15.252471       1 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.5/tools/cache/reflector.go:231: Failed to watch  *v1.Node: failed to list *v1.Node: field label not supported: metadata.namespace
W0908 12:40:39.965420       1 reflector.go:533] pkg/mod/k8s.io/client-go@v0.27.5/tools/cache/reflector.go:231: failed to list *v1.CertificateSigningRequest: field label not supported: metadata.namespace
E0908 12:40:39.965531       1 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.5/tools/cache/reflector.go:231: Failed to watch *v1.CertificateSigningRequest: failed to list *v1.CertificateSigningRequest: field label not supported: metadata.namespace                               
W0908 12:40:52.773607       1 reflector.go:533] pkg/mod/k8s.io/client-go@v0.27.5/tools/cache/reflector.go:231: failed to list *v1.Namespace: field label not supported: metadata.namespace
E0908 12:40:52.773671       1 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.5/tools/cache/reflector.go:231: Failed to watch *v1.Namespace: failed to list *v1.Namespace: field label not supported: metadata.namespace
```
Also on that cluster metrics like `kube_node_info` do not exist anymore (this correlates to the error message about `v1.Node` does not have a field label `metadata.namespace`).

There is a single difference in configuration - the use of `--namespaces-denylist=NAMESPACE_TO_EXCLUDE`. Therefore I assume that this configuration produces the error. If I remove that configuration option it also works on that exact cluster.

**What you expected to happen**:

I expect to have metrics like `kube_node_info` and no exported metrics for namespaces on the denylist.

**How to reproduce it (as minimally and precisely as possible)**:

One just have to add the command line argument `--namespaces-denylist=NAMESPACE_TO_EXCLUDE`. It does not matter if the namespace exists or not.

**Environment**:
- kube-state-metrics version: 2.10.0
- Kubernetes version (use `kubectl version`): 1.27.x (also tested on 1.26.x)
- Cloud provider or hardware configuration: Scaleway, DigitalOcean
- The image was provided by bitnami:  docker.io/bitnami/kube-state-metrics:2.10.0-debian-11-r0 (but I don't think this makes a difference)

### PR DESCRIPTION
**Pull request by dgrisonnet**
This PR takes over the initial work started by @mrueg in https://github.com/kubernetes/kube-state-metrics/pull/2189 and fix the additional cluster-scoped resources that were missing.

**What this PR does / why we need it**:

This should resolve the issue with namespace-denylist as discovered in https://github.com/kubernetes/kube-state-metrics/issues/2187

Regression introduced in https://github.com/kubernetes/kube-state-metrics/commit/c3c552821af3432afdaedec607f43ba1efba1be0

I'm not sure if the fix is complete or other resources are affected. I'm also not sure if this is the right fix or we should simply keep the field selector but fail if the field doesn't exist.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2187

### CODE REVIEW

**Comment by dgrisonnet** [comment]
For reference, the list of cluster-scoped resources in a cluster can be gathered by running:

```sh
{ for api in $(k get --raw /apis | jq -r '.groups[].preferredVersion.groupVersion') ; do k get --raw /apis/$api | jq '.resources[] | select(.namespaced == false) | select(.name | test("^\\w+$")) | .kind' ; done & k get --raw /api/v1 | jq '.resources[] | select(.namespaced == false) | select(.name | test("^\\w+$")) | .kind' } | sort | uniq
```

which in a simple kind cluster yields:

```
"APIService"
"CertificateSigningRequest"
"ClusterRole"
"ClusterRoleBinding"
"ComponentStatus"
"CSIDriver"
"CSINode"
"CustomResourceDefinition"
"FlowSchema"
"IngressClass"
"MutatingWebhookConfiguration"
"Namespace"
"Node"
"PersistentVolume"
"PriorityClass"
"PriorityLevelConfiguration"
"RuntimeClass"
"SelfSubjectAccessReview"
"SelfSubjectReview"
"SelfSubjectRulesReview"
"StorageClass"
"SubjectAccessReview"
"TokenReview"
"ValidatingWebhookConfiguration"
"VolumeAttachment
```

**Comment by mrueg** [comment]
Thanks for taking over!

/lgtm

/hold

**Comment by rexagod** [comment]
(owing to @dgrisonnet's neat one-liner above) I can see that all `kind`s supported in KSM from the listed pool have been addressed. Kudos for swift patch, @mrueg and @dgrisonnet!

/lgtm

**Comment by zombar** [comment]
Any ideas as to a timeframe when this will be included in a release?

This issue would manifest as an unpleasant surprise to those that are blindly upgrading their node-pools as 'watch' and 'get' actions for any non-namespaced resources will fail due to API validation. 

The issue manifests itself as a fairly innocent log entry:
```
E0928 09:10:20.987352       1 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.5/tools/cache/reflector.go:231: Failed to watch *v1.Node: failed to list *v1.Node: field label not supported: metadata.namespace
```
But in this case we would receive no node metrics at all.

PersistentVolumes are also cluster scoped resources and KSM produces metrics from those resources that are useful to all so I might be tempted to get this fix out sooner rather than later.

**Pull request merged**
