### PR TITLE
CHANGELOG: apply changes for v2.1.1

### PR DESCRIPTION
**Pull request by dgrisonnet**
Apply changes mentioned in https://github.com/kubernetes/kube-state-metrics/pull/1540#discussion_r678887849 and https://github.com/kubernetes/kube-state-metrics/pull/1540#discussion_r678890854.

/assign @mrueg

### CODE REVIEW

**Comment by mrueg** [comment]
Thanks @dgrisonnet!

/lgtm

**Comment by mrueg** [comment]
Ah looks like I can't /lgtm on this branch since I was only added as an approver in the default branch :joy: 

@lilic @brancz @tariq1890 can you help out here?

**Review by lilic — APPROVED** [review]
/lgtm

@mrueg you can also carry a patch to the OWNERS file if you want to 2.1? :D

**Comment by mrueg** [comment]
> /lgtm
> 
> @mrueg you can also carry a patch to the OWNERS file if you want to 2.1? :D

Thanks! Hope we can move forward with k8s 1.22 and a ksm-2.2 branch in a week or so :D

**Pull request merged**
