### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by gtorre**
Small update that fixes the syntax of the deployment; useful if using the default deployment file provided.

### CODE REVIEW

**Comment by tariq1890** [comment]
@gtorre Thanks for your PR but it looks like you'd need to sign the CLA with the same email as your git commit.

**Comment by gtorre** [comment]
Updated my profile to expose my email on commits (for CLA purposes.)

**Comment by gtorre** [comment]
Thanks @tariq1890 everything is setup correctly now!

**Comment by tariq1890** [comment]
Thank you very much for your contribution @gtorre :).

/lgtm

**Pull request merged**
