### PR TITLE
refactor: KSM Cyclomatic fix for Job and PV files

### PR DESCRIPTION
**Pull request by venkatbvc**
Fixed cyclomatic complexity for Job.go and persistentVolume.go files 
Changes to be committed:
	modified:   internal/store/job.go
	modified:   internal/store/persistentvolume.go

**What this PR does / why we need it**:
Fix the cyclomatic complexity for job.go and persistentVolume.go
**How does this change affect the cardinality of KSM**: *(increases, decreases or does not change cardinality)*
No change to cardinality
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
Fixes partially 1887

### CODE REVIEW

**Comment by venkatbvc** [comment]
@rexagod  Pushed changes for Job.go and persistentVolume.go. Please review

**Comment by venkatbvc** [comment]
@rexagod @CatherineF-dev @fpetkovski can you please review and share your comments

**Comment by CatherineF-dev** [comment]
Reviewed internal/store/job.go.

If you split this PR into two PRs (job and pv), I think the job one can be merged asap.

**Comment by venkatbvc** [comment]
@CatherineF-dev  I reverted the pv changes. Please check.

**Comment by CatherineF-dev** [comment]
/lgtm 

Waiting @rexagod's review

**Comment by venkatbvc** [comment]
@rexagod can you please review?

**Comment by rexagod** [comment]
Hello, @venkatbvc. Thank you for the PR, however, there's some development recently that affects the areas covered by the parent issue. With the [CEL](https://github.com/kubernetes/kube-state-metrics/issues/1978) and [CRD](https://github.com/kubernetes/kube-state-metrics/issues/1948) changes planned for the near future, we are again going to need to check for any lint (warn-level, that do not block the CI) issues again once those changes are in.

I think it's better to stall this for now and resume this effort once that is done with to avoid repeating the same effort. In the meantime, if you're looking for a `good-first-issue` we've got this: https://github.com/kubernetes/kube-state-metrics/issues/1903 that's been there for a while, and I'd be happy to help with anything around it! 🙂

**Comment by rexagod** [comment]
/hold
Until aforementioned factors clear up.

**Comment by venkatbvc** [comment]
@rexagod Sure we will wait. This week i am little busy.  i will get in touch with you next week

**Pull request closed without merging**
