### PR TITLE
Cleanup doc structure

### PR DESCRIPTION
**Pull request by sarahjanenewnham**
**What this PR does / why we need it**:
Cleanup doc structure as per #1903:
- Create new subdirectories in /docs that align with [Kubernetes API docs](https://kubernetes.io/docs/reference/kubernetes-api/)
- Move all exposed metrics markdown specs appropriate subdirectories
- Move CLI argument docs into /developer
- Update README links as needed
- Update docs test as needed

**How does this change affect the cardinality of KSM**: *(increases, decreases or does not change cardinality)*
does not change cardinality

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Cleanup #1903

### CODE REVIEW

**Comment by sarahjanenewnham** [comment]
Thanks for taking a look @mrueg. I'll make those changes and push an update

**Comment by sarahjanenewnham** [comment]
Apologies for the delay on this. I've got COVID at the moment, but will get back to it as soon as I'm feeling better.

**Comment by mrueg** [comment]
No need to apologize, get well soon and take your time to recover!

**Pull request closed without merging**
