### PR TITLE
add nvidia gpu monitoring

### PR DESCRIPTION
**Pull request by lgarithm**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kube-state-metrics/249)

### CODE REVIEW

**Comment by lgarithm** [comment]
CLA signed

**Comment by brancz** [comment]
Can you comment on the stability guarantees this has, similarly as to what we've discussed for the metrics of GPU resources of Pods? (https://github.com/kubernetes/kube-state-metrics/pull/218)

**Comment by lgarithm** [comment]
@brancz done, PTAL.

**Comment by brancz** [comment]
lgtm, @andyxning do you want to give this a review as well?

**Comment by andyxning** [comment]
Also lgtm.

/lgtm

merging

**Pull request merged**
