### PR TITLE
Reference closure scoped family generator

### LINKED ISSUE #1239: tags/labels missing for daemonset, deployment, and replicaset metrics
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
metrics for daemonset, deployment, and replicaset no longer export tags/labels

**What you expected to happen**:
metrics for daemonset, deployment, and replicaset to include tags/labels

**How to reproduce it (as minimally and precisely as possible)**:
create daemonset, deployment, or replicaset.  poll kube-state-metrics endpoint.  look at, for example, kube_replicaset_created metrics.  observe no tags/labels are attached to it.

**Anything else we need to know?**:
v1.9.7 does not exhibit this issue.  below is a sample comparison with kube_*_created.  the same behavior is observed with all daemonset, deployment, and replicaset metrics.

v2.0.0-alpha:
kube_replicaset_created 1.600788121e+09

kube_deployment_created 1.600788121e+09

kube_daemonset_created 1.600790245e+09=

kube_configmap_created{namespace="openshift-console",configmap="console-config"} 1.600780846e+09

v1.9.7:
kube_replicaset_created{namespace="openshift-console",replicaset="console-fcbd85f55"} 1.600780846e+09

kube_deployment_created{namespace="openshift-web-console",deployment="webconsole"} 1.600780806e+09

kube_daemonset_created{namespace="openshift-node",daemonset="sync"} 1.600780702e+09

kube_configmap_created{namespace="openshift-console",configmap="console-config"} 1.600780846e+

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-10-15T09:45:30Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2020-09-04T19:45:00Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- Kube-state-metrics image version
quay.io/coreos/kube-state-metrics:v2.0.0-alpha

### PR DESCRIPTION
**Pull request by jw-s**
Signed-off-by: Joel Whittaker-Smith <jdws.dev@gmail.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1239

### CODE REVIEW

**Comment by lilic** [comment]
Hey, thanks for this! Will test this out. I changed the base to release-2.0 as per our [release process](https://github.com/kubernetes/kube-state-metrics/blob/master/RELEASE.md).

There are some failing unit tests it seems, do you mind fixing those:
> --- FAIL: TestFullScrapeCycle (1.01s)
    main_test.go:379: expected:
        
        kube_pod_labels{namespace="default",pod="pod0"} 1, but got:
        
        kube_pod_labels{pod="pod0",namespace="default"} 1

**Review by lilic — COMMENTED** [review]
Tested and this does fix the bug, thanks again! Just few things left from my previous comment after that we can merge 🎉

**Comment by jw-s** [comment]
> Hey, thanks for this! Will test this out. I changed the base to release-2.0 as per our [release process](https://github.com/kubernetes/kube-state-metrics/blob/master/RELEASE.md?rgh-link-date=2020-09-28T07%3A58%3A18Z). Do you mind rebasing with the release-2.0 branch as well, thanks!
> 
> There are some failing unit tests it seems, do you mind fixing those:
> 
> > --- FAIL: TestFullScrapeCycle (1.01s)
> > main_test.go:379: expected:
> 
> ```
>     kube_pod_labels{namespace="default",pod="pod0"} 1, but got:
>     
>     kube_pod_labels{pod="pod0",namespace="default"} 1
> ```

Seems like a flaky test. It's passing now...

**Comment by lilic** [comment]
Do you mind just for now only including only your patch, so the last commit in this PR against release-2.0, we can do the rest of the 2.0 merges from master as not all are relevant for the release-2.0 branch. Hope that makes sense? Thanks!

**Comment by jw-s** [comment]
@lilic done but the flaky test is failing again, it's weird as the order shouldn't matter since we sort the strings...

**Comment by lilic** [comment]
Seems like now the tests failed two times in a row, will rerun, if it passes will open an issue to look into it.

**Review by lilic — COMMENTED** [review]
/lgtm

Thanks again!

**Comment by jimmyseto** [comment]
@jw-s - thanks for this PR!

@jw-s @lilic - in testing the latest off the release-2.0 branch, i'm able to confirm that we now get tags/labels for most of the metrics.  but, i notice that the kube_*_label metrics still don't have them.  is this an expected change for v2.0 to reduce/limit cardinality?

**Comment by lilic** [comment]
@jimmyseto yes, this is expected. https://github.com/kubernetes/kube-state-metrics/releases/tag/v2.0.0-alpha let me know if its not clear from the changelog, this is the PR that introduces a flag to control this https://github.com/kubernetes/kube-state-metrics/pull/1125 and issue https://github.com/kubernetes/kube-state-metrics/issues/1047. 

@brancz to double-check as he helped that effort.

**Comment by jimmyseto** [comment]
> @jimmyseto yes, this is expected. https://github.com/kubernetes/kube-state-metrics/releases/tag/v2.0.0-alpha let me know if its not clear from the changelog, this is the PR that introduces a flag to control this #1125 and issue #1047.
> 
> Help in testing the new flag is always appreciated!
> 
> @brancz to double-check as he helped that effort.

thanks for the pointer, @lilic.  i tried using the flag, but it doesn't seem to be working.  or, perhaps, i'm not using it correctly.  here's an example:

> kubectl describe pod kube-state-metrics-756fb7d894-x6f22
...
Labels:        app.kubernetes.io/name=kube-state-metrics
                    app.kubernetes.io/version=2.0.0-alpha
                    pod-template-hash=3129638450
                    testlabel=foobar
...
Containers:
  kube-state-metrics:
...
    Args:
      --resources=pods
      --labels-allow-list=kube_pod_labels=[testlabel]
...

> curl -s -X GET http://kube-state-metrics.kube-system.svc.cluster.local:8080/metrics |grep pod_labels
# HELP kube_pod_labels Kubernetes labels converted to Prometheus labels.
# TYPE kube_pod_labels gauge
kube_pod_labels 1
...

also, with the new flag, is it possible to use wildcards to get all labels for a given metric?

**Comment by jw-s** [comment]
@jimmyseto labels are prefixed with `label_` for labels and `annotation_` for annotations. I can confirm it working with `--labels-allow-list=kube_pod_labels=[namespace, label_app]` for example

**Comment by jimmyseto** [comment]
> @jimmyseto labels are prefixed with `label_` for labels and `annotation_` for annotations. I can confirm it's working with `--labels-allow-list=kube_pod_labels=[namespace, label_app]` for example.
> Wildcards are not currently supported for labels. By default all non _labels/_annotations metrics include all their labels.

thanks @jw-s .  that did the trick.  forgot about the prefix.

i do think it would be helpful to support wildcards.  i can see scenarios in which users may just want to scrape all labels for a particular k8s resource, not knowing exactly what they are looking for.  are there plans to add support for this?

**Comment by lilic** [comment]
> i do think it would be helpful to support wildcards. i can see scenarios in which users may just want to scrape all labels for a particular k8s resource, not knowing exactly what they are looking for. are there plans to add support for this?

@jimmyseto sounds good, feel free to open an issue for it so we can discuss there! 🎉 Thanks!

**Comment by jimmyseto** [comment]
> > i do think it would be helpful to support wildcards. i can see scenarios in which users may just want to scrape all labels for a particular k8s resource, not knowing exactly what they are looking for. are there plans to add support for this?
> 
> @jimmyseto sounds good, feel free to open an issue for it so we can discuss there! 🎉 Thanks!

will do!  thanks!

**Comment by jimmyseto** [comment]
> > > i do think it would be helpful to support wildcards. i can see scenarios in which users may just want to scrape all labels for a particular k8s resource, not knowing exactly what they are looking for. are there plans to add support for this?
> > 
> > 
> > @jimmyseto sounds good, feel free to open an issue for it so we can discuss there! 🎉 Thanks!
> 
> will do! thanks!

created https://github.com/kubernetes/kube-state-metrics/issues/1246

**Pull request merged**
