### PR TITLE
v2: Rename storage class labels reclaimPolicy to reclaim_policy and volumeBindingMode to volume_binding_mode

### LINKED ISSUE #981: v2: Rename storage class labels reclaimPolicy to reclaim_policy and volumeBindingMode to volume_binding_mode
Rename storage class labels reclaimPolicy to reclaim_policy and volumeBindingMode to volume_binding_mode.

This is blocked on merging until after v1.9.0 release.

### PR DESCRIPTION
**Pull request by Dingshujie**
**What this PR does / why we need it**:
Rename storage class labels reclaimPolicy to reclaim_policy and volumeBindingMode to volume_binding_mode
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #981

### CODE REVIEW

**Comment by LiliC** [comment]
/hold 

until the release.

**Comment by lilic** [comment]
@Dingshujie friendly ping :) thanks!

**Pull request closed without merging**
