### PR TITLE
cloudbuild.yaml: Add builds for k8s.gcr.io

### PR DESCRIPTION
**Pull request by lilic**
I do not know if I am doing correctly, we have push make target, which should do the trick but not sure about the name part?

@serathius Marek do you mind having a look, thanks so much!

Background -> https://github.com/kubernetes/kube-state-metrics/issues/1089

### CODE REVIEW

**Comment by lilic** [comment]
PR in test-infra https://github.com/kubernetes/test-infra/pull/17916

**Comment by tariq1890** [comment]
/hold until the test-infra changes are merged

Thanks @lilic !

**Pull request merged**
