### PR TITLE
Update golang-1.16 in Make/Dockerfile / Update promtool to 2.25.2

### PR DESCRIPTION
**Pull request by mrueg**
**What this PR does / why we need it**:
Updates golang version in Makefile and Dockerfile to 1.16.2
Updates prometheus promtool version to 2.25.2

### CODE REVIEW

**Comment by lilic** [comment]
Thanks, is this cherry-pick or a merge, we prefer to merge from the release-2.0 branch? If its a merge then all good just wanted to double check. :)

**Comment by mrueg** [comment]
I'll need to extend it a bit with the dep updates, then it should be ready to go.

**Comment by mrueg** [comment]
@lilic this should be good to go now

**Review by lilic — APPROVED** [review]
/lgtm

thank you!

**Pull request merged**
