### PR TITLE
Ignore metrics if node is removed

### LINKED ISSUE #1380: Metrics about removed node still exported
**What happened**:
Metrics still appear after a node has been removed from the cluster.
The metric is 
`kube_node_status_condition{condition="Ready",...,node="kubeX", status="true"} 0`
Kubectl has no result for this node, and it's no even alive. 

**What you expected to happen**:
Those metrics shouldn't appear.

**How to reproduce it (as minimally and precisely as possible)**:
I haven't tried it in an isolated set up. But I think the use case is clear.

**Anything else we need to know?**:

**Environment**:
- kube-state-metrics version: v1.9.7
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: on-premise
- Other info: -

### PR DESCRIPTION
**Pull request by kei6u**
**Which issue(s) this PR fixes**:
Fixes #1380

### CODE REVIEW

**Comment by fpetkovski** [comment]
I am not sure if this is the best way to fix the problem. This PR is treating the nodes differently from other kubernetes resources, but the behavior should be the same for pods, services and any other resource in the API. 

In addition, I just tried reproducing the issue by deleting a node from a cluster and KSM metrics removed all the series for that node. This leads me to believe that the issue reported in #1380 might actually be the same as https://github.com/kubernetes/kube-state-metrics/issues/694.

**Comment by dgrisonnet** [comment]
I agree with @fpetkovski here, the issue you are experiencing with stale node metrics might be caused by an extended apiserver outage,

**Comment by kskumgk63** [comment]
@fpetkovski @dgrisonnet 
Thanks for your review. 
Do you have any ideas to solve this issue?

**Comment by fpetkovski** [comment]
I think the staleness problem is still under investigation since no one has been able to reproduce it reliably in a development environment yet. How often does this problem happen for you? Is it something that you see once in a while, or is it a regular occurence?

**Comment by aclowkey** [comment]
Hi,
I didn't test it thoroughly. It was a reported *once* in my organization.
It has been a while and it wasn't reported since.

I'm not sure how much context I can give to this issue since so much time
has passed.

**Comment by fpetkovski** [comment]
In that case, I would say that this is an indication of the issue being related to the staleness problem reported in https://github.com/kubernetes/kube-state-metrics/issues/694. My suggestion would be to follow that issue instead.

**Pull request closed without merging**
