### PR TITLE
add go modules support for kube-state-metrics

### LINKED ISSUE #658: Change dependency management tool for kube-state-metrics
Godeps is too old and we should really try changing it to a more mature tool like `dep` or `go.mod`

My vote is for dep. Here are the reasons why

i) `dep` is the more mature tool (for now) and easy to use.
ii) A good number of OSS projects use `dep`
iii) `go.mod` still hasn't reached that level of maturity yet and we should wait until newer versions for Go are release. Moreover, `go.mod` provides an easy transition out of `dep`. Once go modules achieves good stability and adoption rates, the conversion should be easy.

Thoughts @brancz @andyxning @mxinden @zouyee ?

### PR DESCRIPTION
**Pull request by tariq1890**
Go mod support for kube-state-metrics. Removes Godeps.  Fixes #658

### CODE REVIEW

**Comment by tariq1890** [comment]
Ping!

**Comment by brancz** [comment]
Thanks a lot for taking care of this! Happy to have this done in a follow up, but could you add a CI job that runs `go mod verify`? Thanks!

/approve
/lgtm

**Comment by tariq1890** [comment]
@brancz Sure thing!

**Pull request merged**
