### PR TITLE
Fix golint issues reported by goreportcard #919

### LINKED ISSUE #919: Fix golint issues reported by goreportcard
For more information, refer to: https://goreportcard.com/report/github.com/kubernetes/kube-state-metrics#golint

### PR DESCRIPTION
**Pull request by sebach1**
**What this PR does / why we need it**:
Fixes the golint issues with recent changes.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #919

### CODE REVIEW

**Comment by tariq1890** [comment]
@sebach1 Thanks for your PR :). Please make sure to sign the CLA as [shown here](https://git.k8s.io/community/CLA.md#the-contributor-license-agreement).

**Comment by sebach1** [comment]
I signed it!

**Comment by sebach1** [comment]
I signed it

**Comment by sebach1** [comment]
I signed it!

**Comment by sebach1** [comment]
> I signed it!

Well, I think I made a mistake, cz the cla-bot is not doing the re-check. Local, CLA's identity and GitHub emails are matching, any ideas? :thinking:

**Comment by sebach1** [comment]
I signed it!

**Comment by LiliC** [comment]
Did you manage to find a solution for the CLA?

**Comment by tariq1890** [comment]
@sebach1 Ping :)

**Comment by sebach1** [comment]
> @sebach1 Ping :)

Pong (?

Maybe now works..? It seems ok now on LF's web at least

**Comment by tariq1890** [comment]
Can you amend the commit from 
`Fix golint issues reported by goreportcard #919` to `Fix golint issues reported by goreportcard`?

**Comment by sebach1** [comment]
For sure

**Pull request merged**
