### PR TITLE
update Compatibility matrix

### PR DESCRIPTION
**Pull request by zouyee**

### CODE REVIEW

**Comment by brancz** [comment]
Thanks for taking care of this!

I seem to remember, that when we initially discussed this to have the 4 latest versions in this matrix, if @andyxning can confirm this, I'd say we drop everything up until Kubernetes 1.7 and also drop v0.5 of kube-state-metrics.

**Comment by brancz** [comment]
sgtm

**Comment by zouyee** [comment]
👌

**Comment by andyxning** [comment]
Ping @zouyee :)

**Pull request merged**
