### PR TITLE
[e2e] lint the metrics of ksm

### PR DESCRIPTION
**Pull request by YaoZengzeng**
Signed-off-by: YaoZengzeng <yaozengzeng@huawei.com>

**What this PR does / why we need it**:

This PR is to fix part of #875 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by brancz** [comment]
Have you tested that a violation would cause this to fail? If so this lgtm.

**Comment by YaoZengzeng** [comment]
@brancz Yes, it works fine :)

**Pull request merged**
