### PR TITLE
chore: Prep release v2.13.0

### LINKED ISSUE #2406: When is the next release scheduled? Will it be based on "Debian GNU/Linux 12 (Bookworm)"?
Hi Team,

It seems the last released v2.12.0 is built based on "Debian GNU/Linux 11 (bullseye)" which is going end of life in 2 months (31 Jul 2024) (Ref: https://endoflife.date/debian).

I am assuming next release will be based on the "Debian GNU/Linux 12 (Bookworm)". So the question is when is the next release planned and is it safe assumption that it will be based on "Debian GNU/Linux 12 (Bookworm)"?

Thanks in advance

### PR DESCRIPTION
**Pull request by mrueg**
**What this PR does / why we need it**:
Preparing for next release. 
**How does this change affect the cardinality of KSM**: *(increases, decreases or does not change cardinality)*
None
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2406

### CODE REVIEW

**Comment by CatherineF-dev** [comment]
Use 2.13.0 instead https://github.com/kubernetes/kube-state-metrics/issues/2375

**Comment by grigoni** [comment]
Hi folks
To my understanding there will be no 2.12.x release
This opens two questions:
Will this release also support k8s 1.29.x?
How this project manages CVEs for current supported K8s versions?

thanks
Gianandrea

**Comment by rexagod** [comment]
Can we include https://github.com/kubernetes/kube-state-metrics/pull/2418 as well?

**Comment by rexagod** [comment]
Can we please include https://github.com/kubernetes/kube-state-metrics/pull/2418 as well?

**Comment by rexagod** [comment]
Can we include https://github.com/kubernetes/kube-state-metrics/pull/2418 as well?

**Comment by jeremyrickard** [comment]
Hey folks, do you need any help with these releases? Is there something community members can help with?

**Comment by mrueg** [comment]
Thanks for the offer! There are two more issues, we would want to resolve before the next release: https://github.com/kubernetes/kube-state-metrics/milestone/6

In general, yes. If someone in the community would want to help increasing the release cadence that would be super helpful! Let's chat in #kube-state-metrics in k8s slack.

**Review by rexagod — APPROVED** [review]
/lgtm
/hold

(for others, feel free to unhold)

Thank you for running this! 🙂

**Comment by mrueg** [comment]
/hold cancel 

To move ahead with the release.

**Pull request merged**
