### PR TITLE
Revert init containers resource metrics rework

### PR DESCRIPTION
**Pull request by dgrisonnet**
This PR is a follow-up to https://github.com/kubernetes/kube-state-metrics/pull/1278 which didn't completely revert the original resource metrics rework since it kept the init containers metrics although they are also covered by the Kubernetes resource metrics initiative: https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/1748-pod-resource-metrics

Since reverting changes that we already partially reverted in the past was a bit tedious, I separately removed the metrics that were added and updated the `kube_pod_init_container_resource_limits` and `kube_pod_init_container_resource_requests` to be in sync with the recent changes made to the equivalent container metrics.

This PR removes the following experimental metrics:
```
- kube_pod_init_container_resource_limits_cpu_cores
- kube_pod_init_container_resource_limits_memory_bytes
- kube_pod_init_container_resource_limits_storage_bytes
- kube_pod_init_container_resource_limits_ephemeral_storage_bytes
- kube_pod_init_container_resource_requests_cpu_cores
- kube_pod_init_container_resource_requests_memory_bytes
- kube_pod_init_container_resource_requests_storage_bytes
- kube_pod_init_container_resource_requests_ephemeral_storage_bytes
```

### CODE REVIEW

**Comment by fpetkovski** [comment]
Nice work.
/lgtm

**Comment by mrueg** [comment]
/lgtm
/hold 

@dgrisonnet since it took a while for me to review, feel free to cancel the hold here

**Comment by dgrisonnet** [comment]
I think these changes can still go in as is.

/unhold

**Pull request merged**
