### PR TITLE
Created kube_pod_container_status_waiting_reason

### LINKED ISSUE #255: Report waiting reason as well
It would be neat to report as well why a container is in `Waiting` state, for example, `ContainerCreating`, etc.

I'll try to pull this off but I thought it would be neat to have the issue as well in case I don't :D

### PR DESCRIPTION
**Pull request by caarlos0**
closes #255

1. not sure if this is the better approach to this
2. not sure if those are the only possible waiting reasons. Couldn't find docs on this, poke into the kubernetes source and added the ones I found :(

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kube-state-metrics/256)

### CODE REVIEW

**Comment by andyxning** [comment]
@caarlos0 

Thanks for your contributions!

After some search in Kubernetes, there are no enumerate values or predefined const state values for wait state. We absolutely can define some existing ones but we can not guarantee they will not change in the future Kuberenetes releases. This is feasible. So i  am not in favor of adding this.

**Comment by smarterclayton** [comment]
Just these two are probably enough - ErrImagePull is the most common, and there are a few others.  While they won't change, knowing that you have large numbers of pods waiting for pulls vs anything else is probably a good signal.  I.e. if you suddenly have waits for anything else other than pulling, you're probably experiencing something very broken.

**Comment by caarlos0** [comment]
@smarterclayton exactly, pods keep in `ContainerCreating` when docker is broken on the node, or if weave is out of IP addrs, etc...

would be nice to have metrics about this =)

**Comment by brancz** [comment]
Agreed. We can white-list these reasons and prevent carnality explosion, but still have useful information.

As a side note: it more and more feels like we're building the infra-store rather than time-series, which is not necessarily a bad thing (if using Prometheus 2.0), just a thought. Actually kind of neat.

**Comment by smarterclayton** [comment]
OomKill is huge too.  Right now that has to be inferred from discontinuities in the memory graph.

Yeah, agree on the infra-store side - I have that concern too.

**Comment by caarlos0** [comment]
Hi, can we merge this? Anything else I need to do?

I'm having problems because I don't have this metric :(

**Comment by brancz** [comment]
There is a job failing, you're missing documentation for this metric.

**Comment by caarlos0** [comment]
@brancz oh, will fix that ASAP

**Comment by caarlos0** [comment]
@brancz done, sorry for the delay

**Comment by brancz** [comment]
lgtm :+1: thanks!

**Comment by caarlos0** [comment]
thanks @brancz, 

any eta for a release?

**Comment by brancz** [comment]
I can't give an exact ETA, but it should be happening in the upcoming weeks.

**Comment by caarlos0** [comment]
Nice, thanks!

**Pull request merged**
