### PR TITLE
Add HorizontaPodAutoscaler metrics.

### PR DESCRIPTION
**Pull request by bluecamel**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kube-state-metrics/71)

### CODE REVIEW

**Comment by brancz** [comment]
We'll need you to sign the cla to be able to merge this.

**Comment by bluecamel** [comment]
@brancz I've submitted the request and am waiting for someone else at my organization to sign it.

**Comment by brancz** [comment]
unfortunately because of new changes of the client-go dependency this needs a rebase and updating to use the new version as well. Sorry for the inconveniences.

**Comment by bluecamel** [comment]
No worries.  I'm sorry it's taking so long to get approval, but hopefully we can get it moved through next week.

**Comment by brancz** [comment]
No worries, there are a couple of things I would like to get in before a new release as well, so we're not in a huge hurry with this.

**Comment by brancz** [comment]
Did you hear back regarding the cla? And could you rebase these changes?

**Comment by vnandha** [comment]
Hi @bluecamel 

I am looking for this feature as well. Did you hear back regarding cla?

**Comment by sanderploegsma** [comment]
Still nothing 😞

**Comment by andyxning** [comment]
Close this via #230 since all the metrics wanted in this PR has been implemented in #230 and is available for now in master branch.

**Pull request closed without merging**
