### PR TITLE
Cut 1.0 rc1

### PR DESCRIPTION
**Pull request by brancz**
I'm inviting everyone to review the changelog to make sure I've not missed anything and thoroughly test this to make sure we have a solid 1.0 release.

@andyxning @fabxc @piosz @matthiasr @loburm 

/cc @ethernetdan @julia-stripe

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kube-state-metrics/198)

### CODE REVIEW

**Comment by fabxc** [comment]
👍

**Comment by andyxning** [comment]
And, who is going to push the image to gcr.io. 
This is important as we want users testing this release ASAP.

**Comment by brancz** [comment]
@andyxning I talked to @loburm earlier today and he said he'll take care of it right away.

**Comment by andyxning** [comment]
👏

**Comment by brancz** [comment]
Moving forward here, if there are any mistakes in the changelog please comment here or open an issue so we can make sure everything is correct when we release the final 1.0.

**Comment by andyxning** [comment]
This metric has been removed in favor of kube_node_status_condition.

I have comment on the changelog before the merge, didn't known why it does not show up.😂

**Comment by brancz** [comment]
@andyxning I'm not sure I understand your comment. Is there a mistake?

**Comment by brancz** [comment]
FYI I published an image for testing here: quay.io/coreos/kube-state-metrics:v1.0.0-rc.1

@loburm said he'll push the image to the gcr.io registry within the next half an hour.

**Comment by brancz** [comment]
@loburm just informed me that the image is now also on gcr: gcr.io/google_containers/kube-state-metrics:v1.0.0-rc.1

**Comment by andyxning** [comment]
@brancz Sorry for the unclear comment.

I mean in the changelog we add [`[FEATURE] Add kube_node_status_disk_pressure metric.`](https://github.com/kubernetes/kube-state-metrics/pull/198/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR10). And then we add [another changelog](https://github.com/kubernetes/kube-state-metrics/pull/198/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR3) for removing `kube_node_status_disk_pressure` in favor of `kube_node_status_condition`. 

This maybe ambiguous.

How about we remove [this line](https://github.com/kubernetes/kube-state-metrics/pull/198/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR10) and change [this line](https://github.com/kubernetes/kube-state-metrics/pull/198/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR3) to:
```
[CHANGE] Remove `kube_node_status_ready`, `kube_node_status_out_of_disk`, `kube_node_status_memory_pressure` and `kube_node_status_network_unavailable` metrics in favor of one generic `kube_node_status_condition` metric.
```

**Comment by brancz** [comment]
Absolutely, that was a mistake, thanks for catching. I believe I meant to insert another metric there but made a copy/paste mistake.

**Comment by brancz** [comment]
Actually can't find what I wanted to insert there, so I removed the line and opened a PR for it.

**Pull request merged**
