### PR TITLE
*: cut v1.8.0

### PR DESCRIPTION
**Pull request by tariq1890**

### CODE REVIEW

**Comment by brancz** [comment]
/lgtm

@piosz @loburm @serathius @DirectXMan12 please stand by to push the gcr.io image :)

**Comment by serathius** [comment]
@x13n could you handle it?

**Comment by linki** [comment]
@loburm @piosz Would you mind releasing 1.8.0 on https://gcr.io/google_containers/kube-state-metrics as well?

**Comment by serathius** [comment]
@rf232 could you take care of it?

**Pull request merged**
