### PR TITLE
documentation fixes in kube-state-metrics

### PR DESCRIPTION
**Pull request by tariq1890**
Documentation improvements

### CODE REVIEW

**Comment by brancz** [comment]
Could you squash these changes into two commits? One with the docs changes and one with the hpa test? Then lgtm. Thanks!

**Comment by tariq1890** [comment]
I filed this PR on my backup laptop which I don't have with me.Squashing commits from another laptop seems less starightforward. (I am bad with advanced git as well). Would you be okay with me closing this PR and filing  a new one?

**Comment by brancz** [comment]
Whatever is easiest for you :)

**Pull request closed without merging**
