### PR TITLE
Add CatherineF-dev as reviewer

### PR DESCRIPTION
**Pull request by dgrisonnet**
@CatherineF-dev  thank you for the amazing work you've been doing with the stability framework! I am looking forward to continue working with you. :smile: 

/assign @fpetkovski @mrueg 
/cc @logicalhan @rexagod

### CODE REVIEW

**Review by fpetkovski — COMMENTED** [review]
Thank you @CatherineF-dev and welcome 🎉 

/lgtm
/hold

**Review by rexagod — APPROVED** [review]

**Comment by CatherineF-dev** [comment]
Thanks team! It's my honor to be a reviewer!

**Comment by mrueg** [comment]
/lgtm

Thanks for your contributions :tada: !

**Comment by dgrisonnet** [comment]
Welcome to the team! :tada: 

/unhold

**Pull request merged**
