### PR TITLE
Add uid info in kube_pod_info metric

### LINKED ISSUE #507: Show pod uid in the kube_pod_info metrics
/kind feature

Hi, I'm wondering is it possible to show the pod uid as the label in the kube_pod_info metrics?

Thanks.

### PR DESCRIPTION
**Pull request by WakeupTsai**
**What this PR does / why we need it**:
This PR will add pod uid in the kube_pod_info metrics.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #507

### CODE REVIEW

**Comment by brancz** [comment]
You or your organization need to sign the CLA.

Beyond that, as I mentioned in the original issue, we are currently in the process of releasing a new version of kube-state-metrics, so we are currently not merging feature work.

/hold

**Comment by WakeupTsai** [comment]
@brancz It's ok. I can wait.

**Comment by zouyee** [comment]
The unit-test file need to be updated at the same time. 😄

**Comment by andyxning** [comment]
@WakeupTsai You need to also update the pod test for `kube_pod_info` metric to make the Travis CI green.

**Comment by andyxning** [comment]
Ping @WakeupTsai :)

**Comment by brancz** [comment]
Once CI is fixed we can merge this.

/hold cancel

**Comment by WakeupTsai** [comment]
@brancz sorry for late, I have been updated the test :)

**Pull request merged**
