### PR TITLE
docs: rename the Documentation folder to docs

### PR DESCRIPTION
**Pull request by tariq1890**
`docs` seem to be unanimously chosen folder name for Documentation in GitHub open source projects.

### CODE REVIEW

**Comment by tariq1890** [comment]
Also worth noting is that `docs` is something that GitHub itself recognizes. This is an [example](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch)

**Comment by brancz** [comment]
Neat! I wasn't aware of the extend of `/docs`. This needs a rebase, but looks good to me.

**Comment by zouyee** [comment]
SGTM

**Comment by tariq1890** [comment]
Rebased!

**Pull request merged**
