### PR TITLE
charts: Mark chart as deprecated

### LINKED ISSUE #1392: Decouple helm chart releases from application release stream
**What happened**:
Repository is constantly spamming about new version updates of helm chart and not the application.

**What you expected to happen**:
I expect to have a notification when a new version of the **application** comes out and not of some opinionated contrib part in form of a helm chart.

**How to reproduce it (as minimally and precisely as possible)**:
Just go to https://github.com/kubernetes/kube-state-metrics/releases

**Anything else we need to know?**:

I am working on automatic updates of applications based on github releases. This is something I would like to have in kube-prometheus project and as of today I have 99% of this complete, apart of KSM piece where constant releases break everything up.

**Environment**:
- kube-state-metrics version: 
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Other info:

### PR DESCRIPTION
**Pull request by mrueg**
**What this PR does / why we need it**:
We will migrate this chart to https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-state-metrics

@tariq1890 @lilic @scottrigby 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1392

### CODE REVIEW

**Comment by mrueg** [comment]
/hold 
till the migration is completed.

**Comment by mrueg** [comment]
https://github.com/prometheus-community/helm-charts/pull/854 is the WIP migration.

**Comment by tariq1890** [comment]
/lgtm
/approve

Thanks @mrueg

**Pull request merged**
