### PR TITLE
Add observedGeneration metric for DaemonSets

### LINKED ISSUE #1176: Add DaemonSet observed generation metric
/kind feature

**What happened**:

The correct way to determine whether a previous DaemonSet rollout is complete is by checking the following:

```
observedGeneration == generation &&
currentNumberScheduled == desiredNumberScheduled &&
numberMisscheduled == 0 && 
updatedNumberScheduled == desiredNumberScheduled &&
numberAvailable == desiredNumberScheduled
```

As well as checking that `kube_daemonset_updated_number_scheduled` hasn't changed in some time (as in the rollout hasn't progressed). (big thanks to @tnozicka for all the pointers!)

**What you expected to happen**:

All of those numbers to be available to alert on, but `observedGeneration` is not available.

**How to reproduce it (as minimally and precisely as possible)**:

This is a feature, so no previous kube-state-metrics version has this feature :)

**Anything else we need to know?**:

**Environment**: any
- Kubernetes version (use `kubectl version`): any
- Kube-state-metrics image version: any

@lilic @tariq1890

### PR DESCRIPTION
**Pull request by vishnukarthikl**
**What this PR does / why we need it**:
This adds a new metric from DaemonSet status

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1176

### CODE REVIEW

**Comment by brancz** [comment]
Something about your commit seems off, the CLA check can't recognize you. We will only be able to merge once the CLA check passes.

**Comment by vishnukarthikl** [comment]
Thank you @brancz! Hoping to keep up the contribution. Sure I'll create a new PR for the `kube_daemonset_updated_number_scheduled`

**Comment by brancz** [comment]
We're in somewhat final preparations for getting a first v2 release out, so anything you can help out with is highly appreciated! There is [the checklist](https://github.com/kubernetes/kube-state-metrics/issues/569), but beyond that, if you could go through all metrics and make sure there aren't any inconsistencies, like the one I just mentioned. The idea is to minimize the inconsistencies, so we don't need to do a breaking release again in the foreseeable future :)

**Comment by vishnukarthikl** [comment]
Sounds good. 

Just a thought: If we can somehow add automation to check if metrics are valid, that would be great. All the metrics have convention like `kube_<resourcetype>_path`, so it might be possible to validate the path with existing resource definition. I'm new to this project, so will spend some time going through the code base and provide better insights.

**Comment by brancz** [comment]
If you can figure something out for linting metrics like that, that would be amazing!

**Pull request merged**
