### PR TITLE
fix: typo autosharding

### PR DESCRIPTION
**Pull request by CodeJuan**
**What this PR does / why we need it**:
`audosharding` should be `autosharding`
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by zouyee** [comment]
cla needed

**Comment by CodeJuan** [comment]
I'm sorry, I didn't receive the signin email. Then I try to request to resend email to me, the error is `An attempt to send an e-mail message failed.`

**Comment by LiliC** [comment]
@CodeJuan Try following the instructions on here https://github.com/kubernetes/community/blob/master/CLA.md#the-contributor-license-agreement

We don't know the details about the CLA, so if the steps don't work you can contact email under https://github.com/kubernetes/community/blob/master/CLA.md#troubleshooting

**Comment by CodeJuan** [comment]
@LiliC 
Thank you very much. I have signed the ICLA.

**Comment by CodeJuan** [comment]
> You have successfully signed your document 
CNCF Individual Contributor License Agreement

**Comment by LiliC** [comment]
@CodeJuan you have to make sure its the same email as the one you commited as. I think that might be the catch.

**Comment by CodeJuan** [comment]
I checked the email of commit and email of CLA, they are same. 😭

**Comment by LiliC** [comment]
@CodeJuan sorry about this, can you try to maybe open a new PR, this is a valid contribution!. Sadly we can't influence the CLA, its maintained by the k8s org not us devs. Thanks! If not you can also ask via the email provided in the docs what is happening. :) No worries if you are not willing to go through this, I can open a PR to fix it as well. :)

**Comment by tariq1890** [comment]
+1 to what @LiliC said. Let's not give up on this :).

**Comment by CodeJuan** [comment]
Yep, let me try again.

**Pull request closed without merging**
