### PR TITLE
merge v1.0.1 release back into master

### PR DESCRIPTION
**Pull request by brancz**
I tagged and published the release and pushed the image to `quay.io/coreos/kube-state-metrics:v1.0.1`, and asked @loburm to publish the gcr.io image.

@andyxning @fabxc

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kube-state-metrics/244)

### CODE REVIEW

**Comment by andyxning** [comment]
Friendly ping @loburm for build and push v1.0.1 image to gcr.io. :)

**Comment by AndreaGiardini** [comment]
Gcr image is still not found

**Comment by brancz** [comment]
Pinged some google people again to publish it :slightly_smiling_face:

**Comment by andyxning** [comment]
As it is out of control to publish latest image to gcr.io and we use gcr.io image in deployment config file by default. I suggest we move to `quay.io` as the default registry to make kube-state-metrics release more reliable to end users. :)

**Comment by brancz** [comment]
I was just informed that the image was pushed to gcr.

**Comment by loburm** [comment]
Big apologies for the delay from my side. I was on the vacation for last few weeks.

**Comment by brancz** [comment]
No worries, I was informed of that, everything worked out fine :slightly_smiling_face: .

**Pull request merged**
