### PR TITLE
add image_spec to pod (init)container info

### LINKED ISSUE #1557: kube_pod_container_info only contains sha256 value in image label if container image contains sha256 value
**What happened**:

ingress-nginx is deploying containers with digests in their image paths eg:

```
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
        image: k8s.gcr.io/ingress-nginx/controller:v0.48.1@sha256:e9fb216ace49dfa4a5983b183067e97496e7a8b307d2093f4278cd550c303899
```

kube-state-metrics is generating following lables out of these information:

| label | value |
|------|------|
| `image`| `sha256:ac0e4fe3e6b0716b015e2c3df64404f24ad84eaf33e9ef8520a9ad9d8fe8024f ` |
| `image_id` | `k8s.gcr.io/ingress-nginx/controller@sha256: 44a7a06b71187a4529b0a9edee5cc22bdf71b414470eff696c3869ea8d90a695 ` |

**What you expected to happen**:

following labels in the metrics:

| label | value |
|------|------|
| `image`| `k8s.gcr.io/ingress-nginx/controller:v0.48.1` |
| `image_id` | `k8s.gcr.io/ingress-nginx/controller@sha256: 44a7a06b71187a4529b0a9edee5cc22bdf71b414470eff696c3869ea8d90a695 ` |

or (as these information are coming from Kubernetes `containerStatuses` information) also publish `spec.containers[*].image` from spec as eg `image_spec`.

**How to reproduce it (as minimally and precisely as possible)**:

deploy ingress-nginx and watch the metrics from kube-state-metrics :)

**Anything else we need to know?**:

**Environment**:
- kube-state-metrics version: 2.0.0
- Kubernetes version (use `kubectl version`): v1.20.7
- Cloud provider or hardware configuration: azure/aks
- Other info:

### PR DESCRIPTION
**Pull request by mindw**
**What this PR does / why we need it**:
In a nutshell, a container has three image properties, The spec image, the status image and the ImageID. They are not identical - and only the later two were exposed. This PR fills it up. The change relies on the assumptions that in a real pod object it is impossible to have a state entry without a matching spec entry.

**How does this change affect the cardinality of KSM**: 
adds a label on two of the most common metrics.

**Which issue(s) this PR fixes**:
Fixes #1557

### CODE REVIEW

**Comment by mindw** [comment]
Gentle ping (@fpetkovski).

**Comment by fpetkovski** [comment]
Thanks! 

/lgtm

**Comment by mrueg** [comment]
/lgtm

Thanks!

**Pull request merged**
