### PR TITLE
PR #720 into master

### PR DESCRIPTION
**Pull request by mxinden**
**What this PR does / why we need it**:

Merge https://github.com/kubernetes/kube-state-metrics/pull/720 into master

### CODE REVIEW

**Comment by tariq1890** [comment]
What are the remaining work items for ksm 1.6?

**Comment by brancz** [comment]
Another release candidate, then wait 1 week for big reports.

**Comment by mxinden** [comment]
@tariq1890 @brancz pull request for new release candidate: https://github.com/kubernetes/kube-state-metrics/pull/729

**Pull request merged**
