### PR TITLE
chore: lint README.md

### PR DESCRIPTION
**Pull request by rexagod**
To primarily avoid conflicts and allow for automations.

### CODE REVIEW

**Comment by mrueg** [comment]
We already have https://github.com/DavidAnson/markdownlint-cli2 integration, why do we need another markdown formatter/linter?

**Comment by rexagod** [comment]
`markdownlint-cli2` wasn't able to lint the compatibility matrix, owing to which the [padding logic](https://github.com/kubernetes/kube-state-metrics/pull/2325/files#diff-977ea6224b30c391b77b0ecc744af01f21bc3e813351e5cedc5f5d58f534fe84) would differ before and after the substitution or insertions were performed there. So running a linter that ensured an overall consistent `README.md` format would ensure no merge conflicts happen owing to matrix padding.

**Comment by mrueg** [comment]
> `markdownlint-cli2` wasn't able to lint the compatibility matrix, owing to which the [padding logic](https://github.com/kubernetes/kube-state-metrics/pull/2325/files#diff-977ea6224b30c391b77b0ecc744af01f21bc3e813351e5cedc5f5d58f534fe84) would differ before and after the substitution or insertions were performed there. So running a linter that ensured an overall consistent `README.md` format would ensure no merge conflicts happen owing to matrix padding.

My preference would be a README.md.tpl doc that is authoritative to generate the README.md + a config file, see https://docs.gomplate.ca/usage/ for example.

**Pull request closed without merging**
