### PR TITLE
fix typo in README.md

### PR DESCRIPTION
**Pull request by jangdm**
**What this PR does / why we need it**:
fix metric-server to metrics-server

### CODE REVIEW

**Comment by brancz** [comment]
@lilic if we want to merge something like this do we merge it into the release branch?

**Comment by lilic** [comment]
I would say that would best for now, until we at least have a stable rc, we can do that flow. 

@jangdm thanks for the PR! Do you mind just aiming it towards the release-2.0 branch and we can merge

**Comment by jangdm** [comment]
@lilic then do you mean close is PR,
and make PR again to release-2.0 branch?

**Comment by lilic** [comment]
Sorry for confusion, seems like we did merge something against the master branch so might as well merge this as well :) 

/lgtm

Thanks again!! Sorry for the confusion, we are just in the middle of a major release :)

**Comment by jangdm** [comment]
@lilic It's OK!! Thanks for the merge.

**Pull request merged**
