### PR TITLE
kube-state-metrics-resizer role is no longer needed

### PR DESCRIPTION
**Pull request by pdecat**
**What this PR does / why we need it**:

kube-state-metrics-resizer role is no longer needed as addon-resizer was removed in https://github.com/kubernetes/kube-state-metrics/pull/750

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by brancz** [comment]
These will also have to be removed here https://github.com/kubernetes/kube-state-metrics/blob/776dc28dab12c99de2a0095f7c6236c71a9fc6e9/tests/e2e.sh#L126-L127

**Comment by andyxning** [comment]
@pdecat You need to also update 

`
grep -r kube-state-metrics-role-binding

./kustomization.yaml:- kubernetes/kube-state-metrics-role-binding.yaml

./tests/e2e.sh:kubectl create -f ./kubernetes/kube-state-metrics-role-binding.yaml
`

**Comment by pdecat** [comment]
Indeed, I've removed all references to `kube-state-metrics-role` and `kube-state-metrics-role-binding`.

**Comment by mxinden** [comment]
@pdecat thanks for cleaning these up.

**Pull request merged**
