### PR TITLE
Bump golang version to 1.10.1

### LINKED ISSUE #257: kube-state-metrics consuming too much memory
kube-state-metrics is using >400mb of RAM. It is also very slow when I query `/metrics`. The kubernetes cluster has 2700 job objects. It seems surprising that this would consume 400mb of RAM for metrics aggregation. Below is a pprof top trace. This is running the latest git revision (d316c013fae8965bfb75bafda9453ca2ef54c48f)
```
(pprof) top
Showing nodes accounting for 526.72MB, 86.90% of 606.14MB total
Dropped 148 nodes (cum <= 3.03MB)
Showing top 10 nodes out of 110
      flat  flat%   sum%        cum   cum%
  195.01MB 32.17% 32.17%   202.01MB 33.33%  github.com/prometheus/client_golang/prometheus.makeLabelPairs
  101.26MB 16.71% 48.88%   148.26MB 24.46%  github.com/prometheus/client_golang/prometheus.(*Registry).Gather
   74.28MB 12.26% 61.13%    74.81MB 12.34%  k8s.io/kube-state-metrics/collectors.RegisterJobCollector.func1                                                                 47MB  7.75% 68.89%       47MB  7.75%  github.com/prometheus/client_golang/prometheus.populateMetric
   27.60MB  4.55% 73.44%    30.60MB  5.05%  k8s.io/client-go/pkg/api/v1.codecSelfer1234.decSliceVolume
   23.01MB  3.80% 77.24%    23.01MB  3.80%  runtime.rawstringtmp
   18.97MB  3.13% 80.37%    19.55MB  3.22%  github.com/golang/protobuf/proto.(*Buffer).EncodeStringBytes
   15.50MB  2.56% 82.92%   217.51MB 35.88%  github.com/prometheus/client_golang/prometheus.NewConstMetric
   13.50MB  2.23% 85.15%    14.02MB  2.31%  runtime.mapassign
   10.58MB  1.74% 86.90%    12.71MB  2.10%  compress/flate.NewWriter
```

### PR DESCRIPTION
**Pull request by discordianfish**
Fixes #257 (probably)

I've tried debugging #257 by rebuilding ksm with some more debugging options but after building it with go1.10.1

- memory usage dropped from 300MB-1Gi to pretty stable 55-65MB
- scrape duration went from 3s-timeout to 0.3s-1s.

### CODE REVIEW

**Comment by brancz** [comment]
Interesting that it made such a huge difference. We’ll follow up on this with a patch release as well.

**Comment by brancz** [comment]
The test failure may be related to minikube now defaulting to the kubeadm bootstrapper. We’ll have to investigate (and probably pin to a version)

**Comment by andyxning** [comment]
Maybe a memory pprof can help us to further debug this.

**Comment by andyxning** [comment]
As we has another PR #422 to make kube-state-metrics built with golang image. We should not depends on travis golang version anymore. But we can still make a patch release with #422 as we have bumped golang image version number also to 1.10.1.

**Comment by andyxning** [comment]
I suggest we close this via #422.

**Comment by brancz** [comment]
sounds good to me, closing in favor of #422

**Pull request closed without merging**
