### PR TITLE
fix namespace parameter in README.md #1267

### LINKED ISSUE #1267: There is a problem with the document
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

The [usage part](https://github.com/kubernetes/kube-state-metrics#usage) of `README.md` document dose not match the actual kube-state-metrics program . The paramter `--namespace` is not workable .

```yaml
spec:
  template:
    spec:
      containers:
      - name: kube-state-metrics
        args:
          - '--resources=pods'
          - '--namespace=project1'
```

**What you expected to happen**:

As written in the [code](https://github.com/kubernetes/kube-state-metrics/blob/master/pkg/options/options.go#L88), there should be `--namespaces` rather than `--namespace`.

**How to reproduce it (as minimally and precisely as possible)**:

Modify the `README.md` file.

**Anything else we need to know?**:

Nothing

### PR DESCRIPTION
**Pull request by Wang-Kai**
**What this PR does / why we need it**:

Modify `README.md` document, fix `--namespace` parameter bug, which had deprecated

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Fixes #1267

### CODE REVIEW

**Comment by lilic** [comment]
Nice catches, thanks for the PR, the only thing left is to sign the Kubernetes CLA then we can merge. :) 

https://github.com/kubernetes/kube-state-metrics/pull/1268#issuecomment-712105899

**Comment by Wang-Kai** [comment]
I have signed the Kubernetes CLA .

**Comment by Wang-Kai** [comment]
Is it OK ? Just verify it again.

**Comment by Wang-Kai** [comment]
I have received the agreement email.

**Review by lilic — APPROVED** [review]
Thanks for your contribution!!

/lgtm

**Pull request merged**
