### PR TITLE
[kubernetes 1.8] update client-go(release-5.0) and add k8s.io/api(rel…

### PR DESCRIPTION
**Pull request by zouyee**
- [x] update client-go(release-5.0) for kubernetes 1.8

- [x] add k8s.io/api for kubernetes 1.8

- [ ] migrate DaemonSet, Deployment, ReplicaSet, and StatefulSet from v1beta1 to v1beta2

- [ ] migrate cronjob from v1alpha1 to v1beta1

@andyxning  @brancz PTAL!

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kube-state-metrics/266)

### CODE REVIEW

**Comment by brancz** [comment]
> migrate DaemonSet, Deployment, ReplicaSet, and StatefulSet from v1beta1 to v1beta2

When are the v1beta1 objects targeted for removal, if at all? I would prefer keeping the metrics as is as long as possible, if there are any there breaking changes for us, as it will keep backward compatibility for users of older clusters.

**Comment by zouyee** [comment]
- [ ] keep v1beta1 metrics of  DaemonSet, Deployment, ReplicaSet, and StatefulSet 

- [ ] add v1beta2 metrics of  DaemonSet, Deployment, ReplicaSet, and StatefulSet 

- [ ] add version info in these metrics

- [ ] merge [feture collector](https://github.com/kubernetes/kube-state-metrics/pull/220)
@brancz WDYT?

**Comment by andyxning** [comment]
@brancz According to #265, i think we should keep a single geoup version for a resource, right?

IIUC, we should update to v1beta2 for deployment since it is the latest stable support for deployment.

As a re think about this, i think what the compatibilty promise difference between client-go and kube-state-meteics is that client-go supports different group version support for any resource bit kube-state-metrics does not.

Currently used group version for a resource should also be considered as a compability promise since there are more than one group version available.

**Comment by brancz** [comment]
Sorry if I wasn't clear enough, I meant we in kube-state-metrics support the oldest API available in the latest release. That would mean that we stick to `v1beta1` until those are actually permanently removed (if that actually happens).

**Comment by zouyee** [comment]
Whether we have plans to support multiple versions,such as v1beta1(for backward compatibility) and v1beta2(for new changes) ?
For example, observedGeneration has been changed in apps/v1beta2 StatefulSet observedGeneration from a pointer to an int for consistency.

**Comment by brancz** [comment]
> For example, observedGeneration has been changed in apps/v1beta2 StatefulSet observedGeneration from a pointer to an int for consistency.

Things like that don't make a difference for the generated metric. The point is that we at least need to try to support older APIs, but *must* support latest stable Kubernetes (latest as in latest stable at the point where we release kube-state-metrics).

**Comment by zouyee** [comment]
>Things like that don't make a difference for the generated metric. The point is that we at least need to try to support older APIs, but must support latest stable Kubernetes (latest as in latest stable at the point where we release kube-state-metrics).
ok,I got it,but is it a more appropriate approach to update the versions of client-go and introduce api package which could support new features better?

**Comment by brancz** [comment]
As part of our effort to support as many Kubernetes versions as possible we'll have to hold off on newest APIs and use what will support the most versions.

**Comment by zouyee** [comment]
thank you for your response, I got it

**Comment by andyxning** [comment]
@zouyee The first two tasks has been done in #269 . PTAL.

**Comment by andyxning** [comment]
close this PR via #271 and #269 .

**Pull request closed without merging**
