### PR TITLE
Pod Metric Labels

### PR DESCRIPTION
**Pull request by Nalum**
I want to add the Node Name to the Pod metric labels as I think it make more sense to have that in there rather than or as well as the Node IP.

I also think given that the Node IP is used elsewhere it would be worth adding it to the NodeInfo metric. I'm willing to do this but haven't started on it yet as I'd like input as to which IP to use. I'll open an issue for discussion around that.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kube-state-metrics/52)

### CODE REVIEW

**Comment by Nalum** [comment]
I signed it

**Comment by brancz** [comment]
I feel like we really only need this information on the `kube_pod_info` metric, and all other metrics can be joined onto it. Wdyt @fabxc ?

**Comment by fabxc** [comment]
Yes, this is one arbitrary piece of information added to every single metric of an already uniquely identifiable object. The next person wants another bit and adds another label to it and so on...

It gets particularly interesting when think that `node` is not actually a stable attribute if pods can be live-migrated at some point. Thus all time series of a pod would churn at once even though the pod is still there.

This belongs indeed into `kube_pod_info`.

**Comment by Nalum** [comment]
I'll reduce the change to just having the `NodeName` on `kube_pod_info` if that is preferred.

**Comment by Nalum** [comment]
I also just want to note that I'm running `go version go1.7.3 linux/amd64` and `make test-unit` requires `CGO_ENABLED=1` because of the `-race` flag.

**Comment by brancz** [comment]
@Nalum the Makefile was contributed by google and they require us to leave it as is for now.

Other than that lgtm 👍, thanks for the contribution and sorry that it took so long!

**Pull request merged**
