### PR TITLE
Add ReplicaSet metrics.

### PR DESCRIPTION
**Pull request by dominikschulz**
This PR adds ReplicaSet metrics.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kube-state-metrics/55)

### CODE REVIEW

**Comment by brancz** [comment]
I'm a bit concerned about time-series churn with this one as `ReplicaSet`s are most likely used by `Deployment`s. Just wondering, do you have that many `ReplicaSet`s independent of `Deployment`s that this will make a difference?

**Comment by brancz** [comment]
wdyt @fabxc ?

**Comment by dominikschulz** [comment]
You're probably right about time series churn. Even in a rather small cluster we have a few hundred timeseries for these metrics alone.

wdyt if I make this feature optional?

**Comment by brancz** [comment]
I'm not sure what the benefit of this is as I don't see it being used outside of Deployments, but I'm fine with it as long as it is optional and by default turned off. Let's take this opportunity then to introduce a model to enable or disable certain collectors, can you include that in this PR? I suggest to have all of the collectors enabled by default that are in master right now and allow them to be disabled/enabled in a similar fashion as it is done in the [node-exporter](https://github.com/prometheus/node_exporter). Can you do that @dominikschulz ?

**Comment by brancz** [comment]
After some discussion this doesn't turn out to be such a big problem, as we are already exposing metrics based on `Pod`s, which naturally have a much higher churn than `ReplicaSet`s, and there seem to be no reported problems with `Pod`s. So if you can rebase this, we can work on getting this merged soon.

**Comment by brancz** [comment]
continued with #78

**Pull request closed without merging**
