### PR TITLE
Bump the prometheus version in go modules

### LINKED ISSUE #917: Bump the prometheus dependency in the go.mod file
The prometheus version referenced [here](https://github.com/kubernetes/kube-state-metrics/blob/master/go.mod#L15) is very old and we should ideally be using a newer version. for eg:- https://github.com/prometheus/prometheus/releases/tag/v2.12.0

### PR DESCRIPTION
**Pull request by tsturtz**

### CODE REVIEW

**Comment by tsturtz** [comment]
I signed it

**Comment by tariq1890** [comment]
@tsturtz Thanks for your contribution

i) Please make sure to sign the CNCF CLA with the same email address as git email.
ii) Your commit message contains "Closes #917" which is disallowed by Kubernetes since it contains Keywords that could cause Github to close issues inadvertently.

**Comment by tsturtz** [comment]
oops fixing..

**Comment by tariq1890** [comment]
@tsturtz You will need to run `go mod tidy` and `go mod vendor`. Once done, you can commit the resulting changeset.

**Comment by tsturtz** [comment]
Ah ok I'll have to wait on this until I get to a proper machine ;) /hold

**Comment by tariq1890** [comment]
@tsturtz Thank you for your PR. Due to some compatibility issues with the `promlint` in the latest version of prometheus, we may not be able to take in a recent version of prometheus until we introduce breaking changes.

**Comment by tsturtz** [comment]
Hi @tariq1890 - yes `go mod tidy` is showing any version over 2.5 as invalid:

```
version "v2.6.0" invalid: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```
Thanks for working with me on this.

**Pull request closed without merging**
