### PR TITLE
fix container resource limits metrics, which got dropped btwn 2.0.0-a…

### LINKED ISSUE #1292: kube_pod_container_resource_[limits|requests] metrics missing in v2.0.0-alpha.2
**What happened**:
Since we have recently upgraded our cluster to 1.18 from 1.14, so we are trying out the v2.0.0-alpha.2 version. But we were not able to get any scrape for kube_pod_container_resource_limits, while kube_pod_container_resource_requests is scraping fine for most of the pod (for some stateful pods was also missing).

**What you expected to happen**:

kube_pod_container_resource_limits and kube_pod_container_resource_requests to scrape as per documented 

**How to reproduce it (as minimally and precisely as possible)**:
Run v2.0.0-alpha.2 image pulled from quay.io as a deployment on k8s 1.18 cluster.

**Anything else we need to know?**:

**Environment**:
- kube-state-metrics version: v2.0.0-alpha.2 
- Kubernetes version (use `kubectl version`):
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- Other info:
Seems like regression from #1278 per @jimmyseto mentioned in #1245

### PR DESCRIPTION
**Pull request by jimmyseto**
…lpha.1 and 2.0.0-alpha.2

**What this PR does / why we need it**:
container resource limits metrics got dropped between the v2.0.0-alpha.1 and v2.0.0-alpha.2 releases

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1292

### CODE REVIEW

**Review by lilic — COMMENTED** [review]
Thank you!! Reverting was not super straightforward so missed this!

/lgtm

**Comment by lilic** [comment]
Would you mind porting this to master as well? No worries if not! Thanks again!! 🎉

**Comment by jimmyseto** [comment]
> Would you mind porting this to master as well? No worries if not! Thanks again!! 🎉

Done.  PR is at https://github.com/kubernetes/kube-state-metrics/pull/1294

**Pull request merged**
